// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffFile = { path: string, 
/**
 * Verbatim from `--name-status`: M, A, D, R…, C…
 */
status: string, added: number, deleted: number, binary: boolean, 
/**
 * Whether the client should fetch hunks without being asked.
 */
eager: boolean, 
/**
 * Present for renames.
 */
old_path: string | null, 
/**
 * Whether this file has changes in the **index**, and whether it has changes
 * in the **working tree** — `git status`'s two answers, joined on by path.
 *
 * **Not derivable from `status` above, and that is the point.** This list is
 * `git diff <merge-base>`, so most rows on a PR branch differ from the base
 * because of a *commit* and are otherwise clean. Offering "discard changes"
 * against that list would be offering to throw away nothing on some rows and
 * a commit's content on others, from a menu that cannot tell them apart. The
 * pane's git verbs are drawn from these two instead, so what is offered is
 * exactly what exists: staged → unstage, working-tree → stage, discard.
 *
 * Both `false` is the ordinary case (changed in a commit, clean on disk) and
 * gets no verbs at all.
 */
staged: boolean, unstaged: boolean, };

/**
 * One complete way of answering a thread.
 */
export type Position = { label: string, 
/**
 * The line under the label — why you would pick this one.
 */
sub: string, stance: Stance, 
/**
 * A unified diff, exactly as `git diff` printed it in the agent's scratch
 * worktree. Its presence is what "this position changes code" means; there
 * is no second field that could disagree with it.
 */
patch: string | null, 
/**
 * Present iff `stance.writes_reply()`. For a story position it must contain
 * `{story}`, substituted once the story exists.
 */
reply: string | null, story: StoryDraft | null, };

/**
 * One thread's triage: what the agent made of it, and the ways out.
 */
export type Proposal = { thread_id: string, 
/**
 * You already replied here and the reviewer came back. The card flags it,
 * because a new reply has to stay consistent with what you said before.
 */
continued: boolean, 
/**
 * The agent's assessment: is the reviewer right, what breaks either way.
 */
read: string, 
/**
 * The command it ran in its scratch worktree and what that showed. Absent
 * only when no position changes code — there is nothing to re-prove.
 */
verified: string | null, 
/**
 * Index into `positions` of the one to pre-select.
 */
recommend: number, 
/**
 * Named `positions` on the wire too; the agent's schema calls them options,
 * which collides with `Option`.
 */
positions: Array<Position>, };

/**
 * A whole triage run's output.
 */
export type ProposalSet = { 
/**
 * The PR head the patches were generated against. Re-checked before
 * writing: a force-push in between invalidates every diff.
 */
base_sha: string, proposals: Array<Proposal>, };

/**
 * What you are saying back to the reviewer.
 *
 * One of the three things decided per thread, and deliberately only that. It
 * used to be `Does`, which bundled the stance together with whether code gets
 * written and who writes it — so "agree, and I will fix it by hand" had no
 * spelling. Code is now simply whether the position carries a patch, and who
 * writes it is [`Mode`], chosen by the human rather than proposed by the agent.
 */
export type Stance = "agree" | "reply" | "story";

/**
 * A story to file, when a position defers the point rather than answering it.
 */
export type StoryDraft = { title: string, body: string, };
