// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to rebuild a torn-down worktree so an archived session can be resumed (§2).
 */
export type ArchiveState = { "recovery": "recoverable", name: string, branch: string, head_sha: string, } | { "recovery": "transcript_only" };

export type DiffFile = { path: string, 
/**
 * Verbatim from `--name-status`: M, A, D, R…, C…
 */
status: string, added: number, deleted: number, binary: boolean, 
/**
 * Whether the client should fetch hunks without being asked.
 */
eager: boolean, 
/**
 * Present for renames.
 */
old_path: string | null, 
/**
 * Whether this file has changes in the **index**, and whether it has changes
 * in the **working tree** — `git status`'s two answers, joined on by path.
 *
 * **Not derivable from `status` above, and that is the point.** This list is
 * `git diff <merge-base>`, so most rows on a PR branch differ from the base
 * because of a *commit* and are otherwise clean. Offering "discard changes"
 * against that list would be offering to throw away nothing on some rows and
 * a commit's content on others, from a menu that cannot tell them apart. The
 * pane's git verbs are drawn from these two instead, so what is offered is
 * exactly what exists: staged → unstage, working-tree → stage, discard.
 *
 * Both `false` is the ordinary case (changed in a commit, clean on disk) and
 * gets no verbs at all.
 */
staged: boolean, unstaged: boolean, };

export type Health = { "health": "starting" } | { "health": "ok" } | { "health": "failing", summary: string, } | { "health": "dead" };

/**
 * A question a running session is blocked on.
 *
 * Hooks are one-way and the only daemon-to-agent path is a pty write, so this
 * is the first thing that travels *back*: the agent posts a question, blocks on
 * a long poll, and the answer you give in the overlay is what its tool call
 * returns. Deliberately structured rather than free text, so the overlay renders
 * buttons instead of asking you to type into a terminal you cannot see.
 */
export type Interaction = { id: string, 
/**
 * What the agent is working on, so the card can say which thread this is
 * about without the agent having to repeat it in the question.
 */
thread_id: string | null, question: string, 
/**
 * Optional context: a diff, a file, the reviewer's words. Rendered as-is.
 */
detail: string | null, 
/**
 * What you may answer. Never empty: an open question with no options is a
 * prompt for prose the overlay has no box for.
 */
options: Array<InteractionOption>, asked_at: { secs_since_epoch: number, nanos_since_epoch: number }, 
/**
 * Set when you answer, which is what releases the agent's poll.
 */
answer: string | null, 
/**
 * The words you typed, when the option you picked asked for some.
 */
answer_text: string | null, };

export type InteractionOption = { 
/**
 * What comes back to the agent. Its own vocabulary, not the label, so the
 * prompt can branch on a stable word while the card stays readable.
 */
value: string, label: string, sub: string, 
/**
 * This option wants words with it: the escape hatch, for when none of the
 * others fit. The *value* still comes from the agent's own vocabulary, so it
 * branches on a word it wrote; your text rides along as the reason.
 */
free: boolean, };

/**
 * The PR pass a session was started to run, when it was started as one.
 *
 * **One field rather than two.** `pr` and `command` are inseparable — a pass with
 * no PR means nothing, and a PR with no pass is just a session that happens to be
 * on a branch — so they live in one `Option` and the impossible pair cannot be
 * written down.
 *
 * **What reads `command`, and why a skill cannot answer it.** The instructions
 * live in `skills/` now, so this is no longer "which prompt did the daemon type".
 * It is the five things the daemon has to know *around* the agent rather than
 * inside it: which settle path an exit dispatches to (`spawn::watch_session_exit`),
 * which spawn is handed `ORCH_POST_TOKEN` (`triage::posts_proposals`), that a
 * resolve run may not ask questions (`api::ask`), that one triage pass per PR is
 * enough (`triage::is_triage_of`), and which PR the review bar is reporting on.
 * Every one of those happens before the first turn or after the last.
 *
 * It carries **no opinion about attention.** `Kind::Automation` used to, and the
 * rail demoted a running pass and painted it teal on the strength of it — which
 * went wrong the moment a pass meant "a pane you are watching" as well as "a run
 * nobody is". A session is a session; its state says whether it wants you.
 */
export type Pass = { pr: number, command: string, };

/**
 * One complete way of answering a thread.
 */
export type Position = { label: string, 
/**
 * The line under the label — why you would pick this one.
 */
sub: string, stance: Stance, 
/**
 * A unified diff, exactly as `git diff` printed it in the agent's scratch
 * worktree. Its presence is what "this position changes code" means; there
 * is no second field that could disagree with it.
 */
patch: string | null, 
/**
 * Present iff `stance.writes_reply()`. For a story position it must contain
 * `{story}`, substituted once the story exists.
 */
reply: string | null, story: StoryDraft | null, };

export type ProcKind = { "kind": "managed", command: Array<string>, } | { "kind": "shell", exit_code: number | null, };

/**
 * One thread's triage: what the agent made of it, and the ways out.
 */
export type Proposal = { thread_id: string, 
/**
 * You already replied here and the reviewer came back. The card flags it,
 * because a new reply has to stay consistent with what you said before.
 */
continued: boolean, 
/**
 * The agent's assessment: is the reviewer right, what breaks either way.
 */
read: string, 
/**
 * The command it ran in its scratch worktree and what that showed. Absent
 * only when no position changes code — there is nothing to re-prove.
 */
verified: string | null, 
/**
 * Index into `positions` of the one to pre-select.
 */
recommend: number, 
/**
 * Named `positions` on the wire too; the agent's schema calls them options,
 * which collides with `Option`.
 */
positions: Array<Position>, };

/**
 * A whole triage run's output.
 */
export type ProposalSet = { 
/**
 * The PR head the patches were generated against. Re-checked before
 * writing: a force-push in between invalidates every diff.
 */
base_sha: string, proposals: Array<Proposal>, };

/**
 * What you are saying back to the reviewer.
 *
 * One of the three things decided per thread, and deliberately only that. It
 * used to be `Does`, which bundled the stance together with whether code gets
 * written and who writes it — so "agree, and I will fix it by hand" had no
 * spelling. Code is now simply whether the position carries a patch, and who
 * writes it is [`Mode`], chosen by the human rather than proposed by the agent.
 */
export type Stance = "agree" | "reply" | "story";

export type State = { "state": "starting" } | { "state": "working" } | { "state": "your_turn", since: { secs_since_epoch: number, nanos_since_epoch: number }, reason: TurnReason, } | { "state": "build_failing", summary: string, } | { "state": "error", message: string, } | { "state": "exited" } | { "state": "archived", resumable: boolean, };

/**
 * A story to file, when a position defers the point rather than answering it.
 */
export type StoryDraft = { title: string, body: string, };

/**
 * Why a session is waiting on you.
 *
 * Running in auto-accept mode, permission prompts almost never fire; what
 * actually gates progress is Claude finishing a turn (§2). A completed turn is
 * not a quiet success, it is an idle agent.
 */
export type TurnReason = "turn_complete" | "asked_a_question" | "needs_permission" | "ready" | "interrupted";

export type WorkspaceKind = { "kind": "main" } | { "kind": "worktree", name: string, };
