// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffFile } from "./base.d";

export type Checks = "passing" | "failing" | "pending" | "unknown";

/**
 * One comment in a review thread.
 */
export type Comment = { 
/**
 * REST id. The reply endpoint is keyed on this, not on the GraphQL node id.
 */
database_id: bigint, author: string, body: string, created_at: string, url: string, 
/**
 * The anchored patch text. GitHub hangs it off every comment; only the
 * first one's is worth rendering, so `Thread::diff_hunk` reads that.
 */
diff_hunk: string | null, 
/**
 * You have 👍'd this comment.
 *
 * Fetched because the poll and the resolve flow have to agree on what a
 * thumbs-up means, and only the poll could see one: the detailed thread query
 * did not ask for reactions, so `is_answerable` re-offered every thread the
 * flow had already answered with a 👍 — the review's §3 finding.
 */
viewer_thumbed: boolean, };

export type DiffSummary = { base: string, files: Array<DiffFile>, added: number, deleted: number, };

export type FileDiff = { path: string, hunks: Array<Hunk>, binary: boolean, truncated: boolean, };

/**
 * A path the batch will touch, with its line counts — the data behind the
 * card's `will write renovate.json5 +2 −1` label.
 */
export type FileStat = { path: string, added: number, deleted: number, };

export type Hunk = { old_start: number, new_start: number, header: string, 
/**
 * Unchanged lines skipped before this hunk, so the client can render a
 * fold bar and expand on click.
 */
gap_before: number, rows: Array<Row>, };

export type Pr = { number: number, title: string, url: string, head_ref: string, 
/**
 * The head branch's repo, `owner/name`, for naming it in a refusal.
 */
head_repo: string | null, 
/**
 * May you push to that repo?
 *
 * This is what the `fix-pr` authorship guard asks, and it replaced "is the
 * head repo's owner your login". That test was wrong in both directions: on
 * an org PR the owner is the org, so it refused every PR and made `fix-pr`
 * unusable outside a fork layout — while a same-repo PR passed it only
 * because you happened to own the repo, not because it had established
 * anything about a force-push.
 *
 * Repo-level, so it does not promise a given *branch* is force-pushable;
 * `src/guard.rs` is the other half of that pair (`--force-with-lease` only,
 * never the base branch). `None` means GitHub did not say, and the guard fails
 * closed on it.
 */
head_pushable: boolean | null, base_ref: string, is_draft: boolean, 
/**
 * `MERGEABLE` / `CONFLICTING` / `UNKNOWN`.
 */
mergeable: string, merge_state: string, checks: Checks, 
/**
 * Head commit. `fix-pr` amends and rebases, so this moves on every
 * internal attempt — it is an identity for "has the branch changed since
 * the run gave up", not a provenance record (§8).
 */
head_sha: string | null, 
/**
 * GitHub's sense of resolved — a conversation the comment author closed.
 * Not to be confused with `/api/pr/:number/resolve-run`, which is *our* flow for
 * answering threads and deliberately never closes one.
 */
unresolved: number, 
/**
 * True when `reviewThreads` had another page, so `unresolved` is a floor.
 * Rendered as `50+` rather than `50`, so an under-count cannot silently
 * hide work (§6).
 */
unresolved_capped: boolean, 
/**
 * Of those, the ones whose last word is not yours and which you have not
 * 👍'd. This is the number the rail acts on; `unresolved` is GitHub's.
 */
awaiting_you: number, changes_requested: boolean, 
/**
 * Whether this PR is waiting on you, decided here rather than in four
 * places that each got it slightly differently.
 *
 * A thread you have answered is not your turn even though GitHub still
 * calls it unresolved — closing it is the reviewer's button. A
 * changes-requested review counts only when there are no threads to answer,
 * which is the shape of an objection written in the review body: with
 * threads present it stays set until the reviewer looks again, and treating
 * that as your turn is what made an answered PR sit there amber.
 */
needs_you: boolean, 
/**
 * PRs stacked directly on this one.
 */
children: Array<number>, };

/**
 * PRs where your review is requested — other people's work (§6b).
 *
 * The shape came from an existing `mise run reviews --json` task, which applies
 * a richer ranking than §6b describes: prio labels, personal versus team
 * request, re-review detection, reviewer-count tiebreak. The daemon consumes
 * that shape rather than imposing the one §6b invented.
 */
export type Review = { number: number, title: string, url: string, author: string, 
/**
 * Age in hours, however the source expressed it.
 */
age_hours: number, 
/**
 * Source rank: 0 stopper, 1 prio, 2 requested of you, 3 of your team,
 * 4 re-review, 5 other, 6 sidequest.
 */
prio: number, needs_re_review: boolean, is_draft: boolean, 
/**
 * `conflicts`, `failing checks`, … — non-empty means it is waiting on
 * someone else and sinks to the bottom.
 */
blockers: Array<string>, reviewers: number, 
/**
 * Review cost. Absent until the source grows `changedFiles`; the column is
 * omitted rather than faked (see docs/reviews-json.md).
 */
changed_files: number | null, checks: string | null, };

export type ReviewQueue = { login: string, actionable: Array<Review>, blocked: Array<Review>, total: number, skipped: number, };

/**
 * A pane that cannot be trusted must say so.
 *
 * Silently showing zero reviews when the command is broken is the one failure
 * that would actually cost a colleague a day (§6b), so a non-zero exit,
 * unparseable output or an unknown `version` all land here instead.
 */
export type ReviewState = { "state": "ok" } & ReviewQueue | { "state": "degraded", reason: string, } | { "state": "pending" } | { "state": "off" };

export type Row = { kind: RowKind, old: number | null, new: number | null, text: string, 
/**
 * Byte ranges within `text` that actually differ, for word-level
 * highlighting. Computed here so the browser's main thread never pays for
 * it (§5). Non-overlapping and in ascending order.
 */
words: [number, number][] | undefined, };

export type RowKind = "context" | "del" | "add";

/**
 * An unresolved conversation on a PR.
 */
export type Thread = { 
/**
 * `PRRT_…`. **Not** a resolve target — closing a thread is the comment
 * author's button, never ours — but the join key between a thread and the
 * finding the triage agent returns for it.
 */
id: string, path: string | null, 
/**
 * `null` on an outdated thread; the finding can still stand.
 */
line: number | null, start_line: number | null, original_line: number | null, is_resolved: boolean, is_outdated: boolean, comments: Array<Comment>, 
/**
 * [`Thread::is_answerable`] against the fetch's own viewer, resolved by
 * [`Threads::mark_answerable`] so the SPA does not have to reimplement the
 * rule. Always false straight out of parsing, which has no viewer to judge
 * by.
 */
answerable: boolean, };

/**
 * Where the daemon's GitHub token came from.
 *
 * §6 wants a fine-grained PAT with **read scopes only** — `pull_requests`,
 * `checks`, `contents`, `metadata`. The daemon never pushes; `fix-pr` pushes
 * through the agent's own git credentials, so any write scope here is
 * unnecessary blast radius.
 */
export type TokenSource = "env" | "file" | "gh_cli";
