// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open checkout, as the page needs to see it.
 *
 * `token` is in here because the page holds one per checkout: every call names
 * the daemon it is for, and each daemon compares the token against its own. It is
 * the same value as the host's while one process serves both.
 */
export type Checkout = { 
/**
 * Canonical path, which is also the identity: `main_checkout` is resolved in
 * [`orchd::config::Config::parse`], and comparing an unresolved path against
 * a resolved one silently matches nothing.
 */
path: string, 
/**
 * What to call this checkout on screen. Not a key — see [`Checkout::path`].
 *
 * Usually the last path component. **The parent segment is prefixed when two
 * open checkouts share a leaf** (`work/app` beside `play/app`), because the
 * leaf alone is the name in the rail header, the identity chip and every
 * message that says which checkout an action lands in — and two rows reading
 * `app` make all three useless. Only on a collision: a longer name in a 290px
 * rail is a cost most installs should not pay.
 *
 * Computed over the whole set by [`name_the_set`], so it changes when the set
 * does: closing the checkout that collided gives the other its short name
 * back.
 */
name: string, 
/**
 * Where its daemon answers.
 */
port: number, 
/**
 * What that daemon wants in `x-orch-token`.
 */
token: string, 
/**
 * False for a checkout whose daemon is down. Always true while the only
 * daemon is the process serving this page: a host cannot outlive itself.
 */
live: boolean, 
/**
 * The repository this checkout's daemon polls, `owner/name`, when it has one.
 *
 * The key [`Host::add_checkout`] refuses a second checkout on — see
 * [`polled_repo`] for why it is this value and not the `Repos` pair. `None`
 * for a checkout with no matching remote, and two of those are allowed:
 * refusing them would refuse every local-only checkout after the first.
 */
repo: string | null, 
/**
 * The other open checkout polling the same repository, when there is one.
 *
 * **A clash `add` could not see.** `add` derives the identity from whatever
 * config exists; the daemon derives it from the real `upstream_remote` and
 * reports it, which is the only authoritative answer. A disagreement between
 * the two is named here rather than tolerated in silence — the two daemons
 * cannot see each other's fix runs, and nothing else would ever say so.
 */
clash: string | null, };
