// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffFile, Health, Interaction, Pass, ProcKind, State, WorkspaceKind } from "./base.d";
import type { Checks, FileStat, ReviewState, TokenSource } from "./repo.d";

/**
 * A newer agent build than the one installed.
 */
export type AgentUpdate = { 
/**
 * The mise tool name to upgrade — `claude-code` or `claude`, whichever this
 * checkout pins. Carried rather than assumed so the button upgrades the tool
 * that actually provides the binary.
 */
tool: string, current: string, latest: string, };

/**
 * Work banked out of a rebase's way, as the pane needs it.
 *
 * The ref is sent rather than derived in the SPA, because it is the recovery a
 * person runs by hand (`git stash apply <at>`) and a second spelling of the name
 * is a second thing to keep in step.
 */
export type BankedView = { files: number, at: string, };

/**
 * A write that was attempted and refused. `error` is `gh`'s own words.
 */
export type Failed = { thread_id: string, label: string, what: What, error: string, };

/**
 * Why a triage run cannot start.
 *
 * These are the worktree-readiness gates: the review flow writes into this
 * worktree, and every guarantee downstream — the check ladder, the complete file
 * list, "only what you approved" — assumes the tree starts clean. CI colour and
 * a merge conflict deliberately do **not** appear here; they are signals about a
 * future merge and never touch the branch-local machinery.
 */
export type Gate = { "gate": "dirty", files: Array<string>, } | { "gate": "rebasing" } | { "gate": "fix_pr_running" };

/**
 * Something that is now true on GitHub.
 */
export type Landed = { thread_id: string, 
/**
 * `renovate.json5:161 · bob`, for the report's left column.
 */
label: string, what: What, 
/**
 * It was already there, so nothing was sent. The distinction matters on a
 * retry: "posted" and "already posted" read the same to a reviewer but not
 * to someone deciding whether the retry worked.
 */
already: boolean, 
/**
 * Set on a `Story` row. Not a bare id on the struct, which would be
 * meaningless next to a reply or a reaction — and the report needs the URL
 * too, to show what the reply will actually link to.
 */
story: StoryRef | null, };

/**
 * The batch stopped to wait for you.
 *
 * Reached only when a decision chose `Manual`. The accepted patches are written
 * and committed by then, so you edit a tree that already reflects every other
 * decision — often *why* this thread needed hands. **Nothing has been pushed and
 * nothing posted**, so backing out costs only the local commit.
 */
export type ManualPhase = { 
/**
 * The commit the accepted patches landed in. `/manual/done` checks `HEAD`
 * against it, which is what keeps the phase from resuming onto a branch that
 * moved underneath it.
 *
 * Kept in step with the worktree by `update_phase_head` and written to disk with
 * the rest of the phase, because `fold_in` rewrites shas in both its arms — after
 * a fold the old sha is not even an ancestor of `HEAD`, so nothing can re-derive
 * which commit was ours.
 */
committed: string, 
/**
 * What was already written, for the phase screen's first line.
 */
files: Array<FileStat>, amend: string | null, threads: Array<ManualThread>, 
/**
 * A digest of the decisions half one resolved.
 *
 * The resume re-supplies the whole batch and the daemon re-resolves it from
 * scratch, with only `committed == HEAD` checked — and that says nothing about
 * *which* decisions produced that commit. A decision half one never saw would
 * otherwise post a reply describing code that was never applied.
 */
decisions: string, 
/**
 * Is there a phase here to finish, or only a push to remember?
 *
 * [`remember_push`] needs somewhere durable to say "the daemon pushed this,
 * for these decisions", so a retry after a failed reply is not refused as
 * "the branch moved since triage"; the phase store is the one per-PR record a
 * batch has. But a batch that never stopped for the manual phase has no phase,
 * so that record went in as an entry with empty `threads` — and emptiness was
 * the only thing telling the two apart.
 *
 * Nothing read it that way. The boot log announced "manual phase still open",
 * the review payload served it, and the SPA adopted it: it dropped you on a
 * manual screen with no rows, where `threads.every(…)` is vacuously true and
 * `continue · push and post` was therefore enabled. Worse, the record is
 * cleared only when nothing failed, so it survived exactly when it was wrong.
 * Hence a field rather than a shape a reader has to infer.
 */
open: boolean, };

/**
 * A thread the human said they would handle themselves.
 */
export type ManualThread = { thread_id: string, label: string, 
/**
 * The reviewer's own words, so the phase screen needs no second fetch.
 */
comment: string, 
/**
 * What the card's box held. A starting point, not the comment — you cannot
 * describe work you have not done yet, which is why the real one is written
 * in the phase.
 */
draft: string, };

/**
 * What the failure panel renders.
 *
 * `refused` is the local half saying no — the ladder found a stale patch, the
 * hooks rewrote a file, pre-commit failed. Nothing was committed and nothing was
 * pushed, so every other field is empty and the screen is panel 7 rather than
 * panel 8.
 */
export type PostReport = { refused: string | null, 
/**
 * Whether pressing the same button again could succeed once you have acted on
 * `refused`.
 *
 * A stray file or a failing hook is something you fix and retry; the branch
 * having moved under an open phase is not — that sha will never match again, so
 * restoring the phase for it pins you to a screen whose only button is
 * guaranteed to fail. The SPA needs to tell those apart and the message alone
 * cannot.
 */
retryable: boolean, 
/**
 * Set when the batch is waiting on you. Everything else is empty: the outward
 * half has not run.
 */
manual: ManualPhase | null, 
/**
 * The complete file list the batch wrote, from `git apply --numstat`.
 */
files: Array<FileStat>, 
/**
 * How the fold resolved, including when it fell back to a HEAD amend.
 */
amend: string | null, 
/**
 * The sha now on origin. `Some` means the code cannot be taken back.
 */
pushed: string | null, landed: Array<Landed>, failed: Array<Failed>, skipped: Array<Skipped>, rerequested: Array<string>, held_back: Array<Skipped>, };

/**
 * Per-PR automation state (§8).
 *
 * Retry lives in the prompt, not here: `fix-pr` amends and rebases, so the head
 * SHA changes on every internal attempt and SHA-based provenance is impossible
 * *and* unnecessary. The daemon's job is only to avoid starting a second run
 * and to be honest about a run that gave up.
 */
export type PrAutomation = { "state": "running", session: string, started: { secs_since_epoch: number, nanos_since_epoch: number }, } | { "state": "exhausted", 
/**
 * The head this exhaustion is measured against, once anything knows it.
 *
 * `None` means "not established yet", and the next poll adopts whatever
 * it finds. Two things wrote a wrong answer here before, and both
 * cleared the record on the very next poll — erasing the "gave up, wants
 * you" signal the run had just set. `settle` copied the head from the
 * *previous* poll, which the run's own force-push had already moved past;
 * and a crashed run was demoted with `""`, which can never equal a real
 * sha. Neither could be told apart from you moving the branch.
 */
at_head: string | null, at: { secs_since_epoch: number, nanos_since_epoch: number }, };

export type PrView = { rank: number, 
/**
 * The workspace whose branch set contains this PR's head ref.
 */
workspace: string | null, 
/**
 * A live session in that workspace, so the row can act as a jump link.
 */
session: string | null, number: number, title: string, url: string, head_ref: string, 
/**
 * The head branch's repo, `owner/name`, for naming it in a refusal.
 */
head_repo: string | null, 
/**
 * May you push to that repo?
 *
 * This is what the `fix-pr` authorship guard asks, and it replaced "is the
 * head repo's owner your login". That test was wrong in both directions: on
 * an org PR the owner is the org, so it refused every PR and made `fix-pr`
 * unusable outside a fork layout — while a same-repo PR passed it only
 * because you happened to own the repo, not because it had established
 * anything about a force-push.
 *
 * Repo-level, so it does not promise a given *branch* is force-pushable;
 * `src/guard.rs` is the other half of that pair (`--force-with-lease` only,
 * never the base branch). `None` means GitHub did not say, and the guard fails
 * closed on it.
 */
head_pushable: boolean | null, base_ref: string, is_draft: boolean, 
/**
 * `MERGEABLE` / `CONFLICTING` / `UNKNOWN`.
 */
mergeable: string, merge_state: string, checks: Checks, 
/**
 * Head commit. `fix-pr` amends and rebases, so this moves on every
 * internal attempt — it is an identity for "has the branch changed since
 * the run gave up", not a provenance record (§8).
 */
head_sha: string | null, 
/**
 * GitHub's sense of resolved — a conversation the comment author closed.
 * Not to be confused with `/api/pr/:number/resolve-run`, which is *our* flow for
 * answering threads and deliberately never closes one.
 */
unresolved: number, 
/**
 * True when `reviewThreads` had another page, so `unresolved` is a floor.
 * Rendered as `50+` rather than `50`, so an under-count cannot silently
 * hide work (§6).
 */
unresolved_capped: boolean, 
/**
 * Of those, the ones whose last word is not yours and which you have not
 * 👍'd. This is the number the rail acts on; `unresolved` is GitHub's.
 */
awaiting_you: number, changes_requested: boolean, 
/**
 * Whether this PR is waiting on you, decided here rather than in four
 * places that each got it slightly differently.
 *
 * A thread you have answered is not your turn even though GitHub still
 * calls it unresolved — closing it is the reviewer's button. A
 * changes-requested review counts only when there are no threads to answer,
 * which is the shape of an objection written in the review body: with
 * threads present it stays set until the reviewer looks again, and treating
 * that as your turn is what made an answered PR sit there amber.
 */
needs_you: boolean, 
/**
 * PRs stacked directly on this one.
 */
children: Array<number>, };

export type ProcessView = { id: string, name: string, kind: ProcKind, health: Health, cwd: string, alive: boolean, exit_code: number | null, };

export type Repos = { 
/**
 * Where PRs are opened, e.g. `acme/monorepo`.
 */
upstream: string | null, 
/**
 * Where branches are pushed, e.g. `you/monorepo` (§6's fork flow).
 */
fork: string | null, };

export type RunThreadView = { thread_id: string, location: string, status: ThreadStatus, commit: string | null, note: string | null, };

/**
 * What the overview shows about a run: one row per thread, in plan order.
 */
export type RunView = { session: string, threads: Array<RunThreadView>, 
/**
 * Why the run is over, when it is. `null` means the session is still on it.
 */
ended: string | null, 
/**
 * Commits on the run's branch that its remote does not have.
 *
 * The one thing the overview could not say before: a run finishes with the
 * reviewers answered and the work sitting on nobody's branch but yours, and
 * the only mention of it was whatever prose the agent chose to write in the
 * pane. Measured at the last reconcile of the run's own worktree, so it
 * counts a push made anywhere — not a flag the push button sets.
 */
unpushed: number, };

export type SessionView = { id: string, workspace: string, state: State, pass: Pass | null, 
/**
 * What to call this session — the name you gave it, else Claude Code's own
 * ai-title (`Session::label`). The panes read this and stay out of the
 * precedence.
 */
title: string | null, 
/**
 * Only the name you typed, so the rename prompt can offer it back and an
 * empty answer can mean "go back to the ai-title" rather than "freeze it".
 */
name: string | null, cwd: string, 
/**
 * The branch this conversation is about ([`Session::branch`]), not the tree it
 * sits in. Sent so `orch ls` can answer the question its columns could not:
 * whether two sessions can safely work in parallel. A shared `cwd` means one
 * git index, and two rows on one branch means one branch — and neither was
 * visible from id, workspace and state.
 */
branch: string | null, rank: number, 
/**
 * Whether this is idle time worth counting. A session you just opened is
 * idle but not waiting on you in the sense the rail exists to surface.
 */
wants_attention: boolean, 
/**
 * How long this session has been waiting on you. With 4-6 sessions the
 * cost of the whole tool is measured in agent-minutes spent idle (§2).
 */
waiting_ms: number, created_ms: number, alive: boolean, dirty_count: number, boundary_violations: Array<string>, resumable: boolean, 
/**
 * Whether a turn ever happened here — the SPA gates Fork and the nudge on it,
 * and lists an archived row only when it is true. Named for the file it used to
 * stat; it is now the `had_a_turn` bit, which answers the same question the
 * callers actually meant without a per-snapshot read.
 */
has_transcript: boolean, 
/**
 * What this session is blocked on, waiting for you. The overlay renders it;
 * everything else ignores it.
 */
interaction: Interaction | null, 
/**
 * The conversation this one was cut from. A fork inherits its parent's
 * title, so without this two rows read the same and neither says why.
 */
forked_from: string | null, 
/**
 * Whether this session still owes you the rest of a turn. The nudge is only
 * true of these; every other resumed session is sitting at its prompt done.
 */
interrupted: boolean, 
/**
 * A review that ended by handing its PR's checks to a `fix-pr` run.
 *
 * Here rather than left for the overlay to infer, because the two facts it
 * would have to infer it from arrive apart: the session is marked `Exited`
 * straight away and the run's record only exists once `ensure_pr_worktree` and
 * a spawn have finished. In that gap the overlay would put its finished-review
 * report up and then take it away again a second later, which is a worse thing
 * to show than either state.
 */
handed_off: boolean, };

/**
 * A write that was never tried, and what it is waiting on.
 */
export type Skipped = { label: string, what: What, waiting_on: string, };

/**
 * What the SPA receives on every tick.
 *
 * `TS` is derived under `cfg(test)` only, so `ts-rs` is a dev-dependency and
 * nothing about it reaches the shipped binary. `cargo test` writes
 * `web/snapshot.d.ts` from these definitions, and `web/app.js` type-checks
 * against it — which is what stops a field being renamed here and read by the
 * old name there, the way `pr_age_ms` sat unread and the divergence strip named
 * a ref it had not measured.
 */
export type Snapshot = { 
/**
 * The configured tracker's MCP server name, or `None` for no tracker.
 *
 * Here rather than on `/api/config` because it is read-only to the SPA: a
 * tracker is three fields (`config::Tracker`), one of them a per-site host, so
 * the settings pane shows it and does not offer it — and `Settings` leaves it
 * out so a write of the whole struct cannot replace a hand-edited one.
 */
tracker_server: string | null, workspaces: Array<WorkspaceView>, sessions: Array<SessionView>, prs: Array<PrView>, 
/**
 * Set when the last poll failed; the pane says so rather than showing an
 * empty list.
 */
pr_error: string | null, pr_age_ms: number, 
/**
 * Monotonic counter of completed PR polls; see `Inner::pr_poll`.
 */
pr_poll: number, 
/**
 * A PR fetch is running. The pane spins its refresh icon while it is,
 * however the fetch was started.
 */
pr_polling: boolean, token_source: TokenSource | null, reviews: ReviewState, 
/**
 * Age of the last completed review poll, in ms. `None` before the first.
 * Mirrors `pr_age_ms`.
 */
reviews_age_ms: number, 
/**
 * Monotonic counter of completed review polls; see `Inner::reviews_poll`.
 */
reviews_poll: number, reviews_polling: boolean, automation: { [key in string]: PrAutomation }, repos: Repos, 
/**
 * Main may hold more than one live session (`allow_several_in_main`).
 *
 * Sent because the rail decides whether to offer `+` on main, and the reason
 * it may is a setting the SPA cannot see any other way.
 */
several_in_main: boolean, 
/**
 * The base `behind`/`ahead` are measured against, e.g. `upstream/develop`.
 *
 * Sent because it is a setting: the divergence strip used to print the
 * default as a literal, so on any repo that had edited it the UI named a ref
 * the numbers did not come from.
 */
upstream_ref: string, 
/**
 * `docker compose` stack has running containers; `None` before first probe.
 */
stack_up: boolean | null, 
/**
 * A newer release than the running build, or `None`.
 */
update: UpdateInfo | null, 
/**
 * The app's own upgrade run: `running` while `mise upgrade` goes, then a tail
 * that is empty on success. Success means *installed*, not applied — this
 * process is still the old build, so the bar then asks for a restart.
 */
self_upgrade_run: UpgradeRun | null, 
/**
 * A newer Claude Code than the installed one, or `None`. Actionable in the
 * UI: the upgrade cannot disturb a session already running.
 */
agent_update: AgentUpdate | null, 
/**
 * The upgrade the update bar reports on, while it runs and after it fails.
 */
upgrade_run: UpgradeRun | null, 
/**
 * Resolve runs in flight, by PR: what each thread's outcome was so far. The
 * overview reads this rather than the report of a batch that has finished,
 * because a run is watchable while it happens.
 */
resolve_runs: { [key in string]: RunView }, 
/**
 * How far each triage pass has read, by PR. The review bar counts with it.
 */
triage: { [key in string]: TriageProgress }, 
/**
 * The running build's own version, for the settings panel. Always here,
 * unlike `update`, which only appears when there is something newer: "which
 * build am I on" is a question worth answering when the answer is "the
 * latest one".
 */
version: string, };

/**
 * A story that exists in the tracker.
 *
 * Both halves come from the tool response and neither is ever constructed by
 * `format!`: the org slug in the URL belongs to your tracker workspace and the daemon has no
 * business knowing it.
 */
export type StoryRef = { 
/**
 * Short form, `sc-12345`. What the report shows.
 *
 * Private, with [`StoryRef::new`] the only way in, because the pair is agent
 * text that ends up as a link in a public comment: a value that has not been
 * through [`StoryRef::consistent`] must not be constructible outside this
 * module. Serde is the exception it cannot police — a `stories.json` written
 * before the id was checked deserializes straight past the constructor, which
 * is why [`Cache::get`] re-checks on the way out.
 */
id: string, 
/**
 * The clickable one, `https://app.shortcut.com/<org>/story/12345`.
 */
url: string, };

/**
 * Where one thread of a run has got to.
 *
 * The states a thread can actually be in, rather than done/not-done: a run that
 * answered four threads, held one back and could not apply a sixth has five
 * different outcomes to account for, and an overview that says "5 of 6" about it
 * is hiding the only rows worth reading.
 */
export type ThreadStatus = "pending" | "committed" | "replied" | "held" | "manual" | "words_only" | "needs_you";

/**
 * A resolve run: the session doing it, and the decisions it carries.
 *
 * How far a triage pass has read, and whether it has handed anything over.
 *
 * **The agent is the only thing that can count this.** The daemon knows how many
 * threads it handed over, but the read is a judgement per thread rather than a
 * loop the daemon drives, so the skill posts after each one and this is where it
 * lands. `total` is the agent's own count of what it means to read, which can be
 * fewer than the threads on the PR: an answered thread is skipped, and a bar
 * counting those would never reach its end.
 *
 * In memory only, and deliberately: it is a progress bar for a pass that ends
 * with its session. The proposals themselves are stored, so a restart loses the
 * caption and not the work.
 */
export type TriageProgress = { 
/**
 * Threads read so far.
 */
done: number, 
/**
 * Threads this pass means to read.
 */
total: number, 
/**
 * The proposals have landed, so the cards are there to go to.
 */
posted: boolean, 
/**
 * The session doing the reading, so the bar can refuse to caption another
 * session's pane.
 */
session: string, };

/**
 * A release newer than what is running.
 */
export type UpdateInfo = { current: string, latest: string, url: string, 
/**
 * The mise tool that installed this binary, when one did.
 *
 * What decides whether the bar can offer a button at all: `Some` is an install
 * the app can upgrade itself (`mise upgrade <tool>`), `None` is a `.deb`, an
 * AppImage, a `.dmg` or a checkout, where the honest offer is the release link
 * it already had. Resolved by `update::app_providing_tool` at check time,
 * off-thread, because it shells mise.
 */
tool: string | null, };

/**
 * An upgrade the daemon is running, or the failure it left behind.
 *
 * The run used to be a process in main's drawer, which was the wrong home twice:
 * the drawer is *this workspace's* processes, and upgrading the agent belongs to
 * no workspace — so from any worktree the run was invisible, and main's drawer
 * grew a tab that was not a process of main's at all. It reports through the same
 * bar that offered the button instead.
 */
export type UpgradeRun = { 
/**
 * The version being installed. Carried so the bar can say it even after the
 * check that found it has been refreshed away.
 */
to: string, running: boolean, 
/**
 * The tail of the output, for a run that failed. Empty while it runs, and
 * empty on success — which, with `running` false, is how the bar tells the two
 * finished states apart.
 *
 * Success used to clear the run outright, on the reasoning that the nudge
 * going away *is* the report. It is not: the sessions you have open go on
 * printing Claude Code's own upgrade notice, because they really are still the
 * old build, so a bar that vanishes silently against a terminal that still
 * says "update available" reads as a button that did nothing. It is reported,
 * and dismissed like any other.
 */
tail: string, };

/**
 * A single outward write, named the way the report renders it.
 */
export type What = "story" | "reply" | "thumbs_up" | "rerequest";

export type WorkspaceView = { id: string, path: string, kind: WorkspaceKind, is_main: boolean, occupant: string | null, 
/**
 * Every branch this workspace has ever held, never pruned (§2).
 *
 * Not "what is checked out" — see `branch` for that. The two were conflated
 * once, and the rail offered to swap with a main that was sitting on its base.
 */
branches: Array<string>, 
/**
 * What it has checked out now, or `None` before the first reconcile.
 */
branch: string | null, processes: Array<ProcessView>, 
/**
 * Managed processes this workspace declares that are not running — config
 * order, names only.
 *
 * The drawer built its tabs from `processes` alone, so anything with
 * `autostart: false` had no way into the app at all: the restart button the
 * config comment points at is drawn *on a tab*, and there was no tab. A
 * `docker compose up` you deliberately do not autostart still has to be
 * startable.
 */
stopped_processes: Array<string>, 
/**
 * Uncommitted work the rebase button parked, if any is parked.
 */
banked: BankedView | null, 
/**
 * Every file this workspace changed since it branched, committed work
 * included, plus anything untracked. What the changed-files pane lists.
 *
 * **Capped at [`CHANGED_CAP`]**, with the real number in `changed_total`.
 * That constant carries the measurement and the incident behind it.
 */
changed: Array<DiffFile>, 
/**
 * How many there really are, when `changed` is a prefix of them.
 *
 * Sent rather than inferred from the length, so the pane can say "500 of
 * 5,214" instead of quietly presenting a truncation as the whole answer —
 * the same honesty `unresolved_capped` buys the PR pane (§6).
 */
changed_total: number, 
/**
 * The commit the above is measured from: `merge-base(upstream, HEAD)`.
 */
changed_since: string | null, 
/**
 * Commits on `upstream/develop` this branch does not have. Drives the
 * rebase affordance.
 */
behind: number, ahead: number, rebasing: boolean, 
/**
 * Whether the four fields above have ever been measured for this workspace
 * — see [`crate::model::Tree::measured`].
 *
 * The pane needs it because the first sweep no longer finishes before the
 * window opens: without it an unmeasured worktree renders as "nothing
 * changed", which is the one thing a changed-files pane must not say when it
 * does not know.
 */
measured: boolean, };
