// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffFile } from "./base.d";
import type { Checks, ReviewState, TokenSource, Warning } from "./repo.d";

/**
 * A newer agent build than the one installed.
 */
export type AgentUpdate = { 
/**
 * The mise tool name to upgrade — `claude-code` or `claude`, whichever this
 * checkout pins. Carried rather than assumed so the button upgrades the tool
 * that actually provides the binary.
 */
tool: string, current: string, latest: string, };

/**
 * How to rebuild a torn-down worktree so an archived session can be resumed (§2).
 */
export type ArchiveState = { "recovery": "recoverable", name: string, branch: string, head_sha: string, } | { "recovery": "transcript_only" };

/**
 * Work banked out of a rebase's way, as the pane needs it.
 *
 * The ref is sent rather than derived in the SPA, because it is the recovery a
 * person runs by hand (`git stash apply <at>`) and a second spelling of the name
 * is a second thing to keep in step.
 */
export type BankedView = { files: number, at: string, };

/**
 * What a worktree cut is doing, while it does it.
 *
 * **Cutting a tree is other people's scripts, and they are the slow part.** The
 * repo's `WorktreeCreate` fetches, checks out 18k files and warms git; the
 * configured `worktree_init` and `worktree_setup` run on top. The board said
 * `creating a worktree` for all of it, so ten seconds of real work looked
 * identical to a button that had done nothing.
 *
 * One slot per daemon rather than one per create. Two cuts at once is possible
 * through the API and the board already refuses it (`asTheOnlyCreate`), so a map
 * would buy a key nobody reads for a case nobody can reach from the page.
 *
 * Here in `model` because `orchd`'s `Snapshot` carries it and `state` may
 * not import the modules that fill it — a shape lives in `model`, the module that
 * fills it depends on `model`.
 */
export type CreateRun = { 
/**
 * The worktree being made. Carried so the pane can name it once the create
 * has moved on to a step that does not.
 */
name: string, 
/**
 * The script running now, by the name it is configured under:
 * `WorktreeCreate`, `worktree init`, `worktree setup`.
 */
step: string, 
/**
 * False once the scripts are done. The session's own boot follows, and the
 * board keeps its overlay up for that — so this going false is not the end of
 * the create, only the end of what this reports on.
 */
running: boolean, 
/**
 * What the scripts said, oldest first, capped at [`CREATE_LINES`].
 */
lines: Array<string>, 
/**
 * The step that failed, and how. A worktree hook is never fatal, so a run can
 * carry on past this — it is a note on the output, not a terminal state.
 */
failed: string | null, };

/**
 * A past conversation orchd never started, as the archive draws it.
 *
 * Deliberately not a [`SessionView`] with the fields blanked. There is no state
 * machine behind one, no pty, no branch and no claim on a workspace, and a row
 * that carries those as defaults is a row every reader has to remember is
 * lying. `has_transcript: false` on a conversation that plainly has one is
 * exactly the shape `isConversation` filters away.
 */
export type ExternalView = { id: string, 
/**
 * The workspace whose directory holds the transcript, which is where a resume
 * would put it.
 */
workspace: string, 
/**
 * Claude Code's own `ai-title`. `None` reads as untitled in the rail: there is
 * no name you could have given one of these, and no workspace name worth
 * borrowing, since the workspace is on the row already.
 */
title: string | null, 
/**
 * Age of the last turn. Named `_ms` for the same reason every other age is:
 * `paintSig` drops those keys, so a clock ticking in the snapshot does not
 * rebuild the rail.
 */
last_used_ms: number, 
/**
 * Something was writing to this conversation a moment ago, so it may still be
 * open in a terminal ([`crate::store::recently_active`]).
 *
 * Sent so the rail can ask before it resumes one rather than after: the daemon
 * refuses an unforced resume of a live conversation, and a refusal the page
 * could have predicted is a toast with nothing you can do about it. It is as
 * fresh as the last scan, so the two can disagree for up to a poll — the
 * daemon's own check at the moment of the call is the one that decides.
 */
may_be_live: boolean, };

/**
 * Why a triage run cannot start.
 *
 * These are the worktree-readiness gates: the review flow writes into this
 * worktree, and every guarantee downstream — the check ladder, the complete file
 * list, "only what you approved" — assumes the tree starts clean. CI colour and
 * a merge conflict deliberately do **not** appear here; they are signals about a
 * future merge and never touch the branch-local machinery.
 */
export type Gate = { "gate": "dirty", files: Array<string>, } | { "gate": "rebasing" } | { "gate": "fix_pr_running" };

export type Health = { "health": "starting" } | { "health": "ok" } | { "health": "failing", summary: string, } | { "health": "dead" };

/**
 * A question a running session is blocked on.
 *
 * Hooks are one-way and the only daemon-to-agent path is a pty write, so this
 * is the first thing that travels *back*: the agent posts a question, blocks on
 * a long poll, and the answer you give in the overlay is what its tool call
 * returns. Deliberately structured rather than free text, so the overlay renders
 * buttons instead of asking you to type into a terminal you cannot see.
 */
export type Interaction = { id: string, 
/**
 * What the agent is working on, so the card can say which thread this is
 * about without the agent having to repeat it in the question.
 */
thread_id: string | null, question: string, 
/**
 * Optional context: a diff, a file, the reviewer's words. Rendered as-is.
 */
detail: string | null, 
/**
 * What you may answer. Never empty: an open question with no options is a
 * prompt for prose the overlay has no box for.
 */
options: Array<InteractionOption>, asked_at: { secs_since_epoch: number, nanos_since_epoch: number }, 
/**
 * Set when you answer, which is what releases the agent's poll.
 */
answer: string | null, 
/**
 * The words you typed, when the option you picked asked for some.
 */
answer_text: string | null, };

export type InteractionOption = { 
/**
 * What comes back to the agent. Its own vocabulary, not the label, so the
 * prompt can branch on a stable word while the card stays readable.
 */
value: string, label: string, sub: string, 
/**
 * This option wants words with it: the escape hatch, for when none of the
 * others fit. The *value* still comes from the agent's own vocabulary, so it
 * branches on a word it wrote; your text rides along as the reason.
 */
free: boolean, };

/**
 * What the update bar may offer for this install.
 *
 * Three arms because there are three honest answers, not because there are three
 * install kinds: something the app can run for you, something only you can run,
 * and nothing beyond the release link.
 */
export type Offer = { "kind": "button", command: string, } | { "kind": "advice", command: string, } | { "kind": "link_only" };

/**
 * The PR pass a session was started to run, when it was started as one.
 *
 * **One field rather than two.** `pr` and `command` are inseparable — a pass with
 * no PR means nothing, and a PR with no pass is just a session that happens to be
 * on a branch — so they live in one `Option` and the impossible pair cannot be
 * written down.
 *
 * **What reads `command`, and why a skill cannot answer it.** The instructions
 * live in `skills/` now, so this is no longer "which prompt did the daemon type".
 * It is the five things the daemon has to know *around* the agent rather than
 * inside it: which settle path an exit dispatches to (`spawn::watch_session_exit`),
 * which spawn is handed `ORCH_POST_TOKEN` (`triage::posts_proposals`), that a
 * resolve run may not ask questions (`api::ask`), that one triage pass per PR is
 * enough (`triage::is_triage_of`), and which PR the review bar is reporting on.
 * Every one of those happens before the first turn or after the last.
 *
 * It carries **no opinion about attention.** `Kind::Automation` used to, and the
 * rail demoted a running pass and painted it teal on the strength of it — which
 * went wrong the moment a pass meant "a pane you are watching" as well as "a run
 * nobody is". A session is a session; its state says whether it wants you.
 */
export type Pass = { pr: number, command: string, };

/**
 * Per-PR automation state (§8).
 *
 * Retry lives in the prompt, not here: `fix-pr` amends and rebases, so the head
 * SHA changes on every internal attempt and SHA-based provenance is impossible
 * *and* unnecessary. The daemon's job is only to avoid starting a second run
 * and to be honest about a run that gave up.
 */
export type PrAutomation = { "state": "running", session: string, started: { secs_since_epoch: number, nanos_since_epoch: number }, } | { "state": "exhausted", 
/**
 * The head this exhaustion is measured against, once anything knows it.
 *
 * `None` means "not established yet", and the next poll adopts whatever
 * it finds. Two things wrote a wrong answer here before, and both
 * cleared the record on the very next poll — erasing the "gave up, wants
 * you" signal the run had just set. `settle` copied the head from the
 * *previous* poll, which the run's own force-push had already moved past;
 * and a crashed run was demoted with `""`, which can never equal a real
 * sha. Neither could be told apart from you moving the branch.
 */
at_head: string | null, at: { secs_since_epoch: number, nanos_since_epoch: number }, };

export type PrView = { rank: number, 
/**
 * The workspace whose branch set contains this PR's head ref.
 */
workspace: string | null, 
/**
 * A live session in that workspace, so the row can act as a jump link.
 */
session: string | null, number: number, title: string, url: string, head_ref: string, 
/**
 * The head branch's repo, `owner/name`, for naming it in a refusal.
 */
head_repo: string | null, 
/**
 * May you push to that repo?
 *
 * This is what the `fix-pr` authorship guard asks, and it replaced "is the
 * head repo's owner your login". That test was wrong in both directions: on
 * an org PR the owner is the org, so it refused every PR and made `fix-pr`
 * unusable outside a fork layout — while a same-repo PR passed it only
 * because you happened to own the repo, not because it had established
 * anything about a force-push.
 *
 * Repo-level, so it does not promise a given *branch* is force-pushable;
 * `src/guard.rs` is the other half of that pair (`--force-with-lease` only,
 * never the base branch). `None` means GitHub did not say, and the guard fails
 * closed on it.
 */
head_pushable: boolean | null, base_ref: string, is_draft: boolean, 
/**
 * `MERGEABLE` / `CONFLICTING` / `UNKNOWN`.
 */
mergeable: string, merge_state: string, checks: Checks, 
/**
 * Head commit. `fix-pr` amends and rebases, so this moves on every
 * internal attempt — it is an identity for "has the branch changed since
 * the run gave up", not a provenance record (§8).
 */
head_sha: string | null, 
/**
 * GitHub's sense of resolved — a conversation the comment author closed.
 * Not to be confused with `/api/pr/:number/resolve-run`, which is *our* flow for
 * answering threads and deliberately never closes one.
 */
unresolved: number, 
/**
 * True when `reviewThreads` had another page, so `unresolved` is a floor.
 * Rendered as `50+` rather than `50`, so an under-count cannot silently
 * hide work (§6).
 */
unresolved_capped: boolean, 
/**
 * Of those, the ones whose last word is not yours and which you have not
 * 👍'd. This is the number the rail acts on; `unresolved` is GitHub's.
 */
awaiting_you: number, changes_requested: boolean, 
/**
 * Whether this PR is waiting on you, decided here rather than in four
 * places that each got it slightly differently.
 *
 * A thread you have answered is not your turn even though GitHub still
 * calls it unresolved — closing it is the reviewer's button. A
 * changes-requested review counts only when there are no threads to answer,
 * which is the shape of an objection written in the review body: with
 * threads present it stays set until the reviewer looks again, and treating
 * that as your turn is what made an answered PR sit there amber.
 */
needs_you: boolean, 
/**
 * PRs stacked directly on this one.
 */
children: Array<number>, };

export type ProcKind = { "kind": "managed", command: Array<string>, } | { "kind": "shell", exit_code: number | null, };

export type ProcessView = { id: string, name: string, kind: ProcKind, health: Health, cwd: string, alive: boolean, exit_code: number | null, };

export type Repos = { 
/**
 * Where PRs are opened, e.g. `acme/monorepo`.
 */
upstream: string | null, 
/**
 * Where branches are pushed, e.g. `you/monorepo` (§6's fork flow).
 */
fork: string | null, };

export type SessionView = { id: string, workspace: string, state: State, pass: Pass | null, 
/**
 * What to call this session — the name you gave it, else Claude Code's own
 * ai-title (`Session::label`). The panes read this and stay out of the
 * precedence.
 */
title: string | null, 
/**
 * Only the name you typed, so the rename prompt can offer it back and an
 * empty answer can mean "go back to the ai-title" rather than "freeze it".
 */
name: string | null, cwd: string, 
/**
 * The branch this conversation is about ([`Session::branch`]), not the tree it
 * sits in. Sent so `orch ls` can answer the question its columns could not:
 * whether two sessions can safely work in parallel. A shared `cwd` means one
 * git index, and two rows on one branch means one branch — and neither was
 * visible from id, workspace and state.
 */
branch: string | null, rank: number, 
/**
 * Whether this is idle time worth counting. A session you just opened is
 * idle but not waiting on you in the sense the rail exists to surface.
 */
wants_attention: boolean, 
/**
 * How long this session has been waiting on you. With 4-6 sessions the
 * cost of the whole tool is measured in agent-minutes spent idle (§2).
 */
waiting_ms: number, created_ms: number, alive: boolean, dirty_count: number, boundary_violations: Array<string>, resumable: boolean, 
/**
 * Whether a turn ever happened here — the SPA gates Fork and the nudge on it,
 * and lists an archived row only when it is true. Named for the file it used to
 * stat; it is now the `had_a_turn` bit, which answers the same question the
 * callers actually meant without a per-snapshot read.
 */
has_transcript: boolean, 
/**
 * What this session is blocked on, waiting for you. The overlay renders it;
 * everything else ignores it.
 */
interaction: Interaction | null, 
/**
 * The conversation this one was cut from. A fork inherits its parent's
 * title, so without this two rows read the same and neither says why.
 */
forked_from: string | null, 
/**
 * Whether this session still owes you the rest of a turn. The nudge is only
 * true of these; every other resumed session is sitting at its prompt done.
 */
interrupted: boolean, 
/**
 * A review that ended by handing its PR's checks to a `fix-pr` run.
 *
 * Here rather than left for the overlay to infer, because the two facts it
 * would have to infer it from arrive apart: the session is marked `Exited`
 * straight away and the run's record only exists once `ensure_pr_worktree` and
 * a spawn have finished. In that gap the overlay would put its finished-review
 * report up and then take it away again a second later, which is a worse thing
 * to show than either state.
 */
handed_off: boolean, 
/**
 * Waiting to be respawned on the `claude` installed now — see
 * [`Session::restart_queued`]. The row says so, because a session that
 * restarts itself the moment you finish a turn is a surprise otherwise.
 */
restart_queued: boolean, 
/**
 * Running an older Claude Code than a new session here would get — see
 * [`Session::agent_stale`]. What the agent bar counts when it offers to
 * restart the sessions an upgrade left behind.
 */
agent_stale: boolean, };

/**
 * What the SPA receives on every tick.
 *
 * `TS` is derived under `cfg(test)` only, so `ts-rs` is a dev-dependency and
 * nothing about it reaches the shipped binary. `cargo test` writes
 * `web/snapshot.d.ts` from these definitions, and `web/app.js` type-checks
 * against it — which is what stops a field being renamed here and read by the
 * old name there, the way `pr_age_ms` sat unread and the divergence strip named
 * a ref it had not measured.
 */
export type Snapshot = { 
/**
 * The configured tracker's MCP server name, or `None` for no tracker.
 *
 * Here rather than on `/api/config` because it is read-only to the SPA: a
 * tracker is three fields (`config::Tracker`), one of them a per-site host, so
 * the settings pane shows it and does not offer it — and `Settings` leaves it
 * out so a write of the whole struct cannot replace a hand-edited one.
 */
tracker_server: string | null, 
/**
 * Workspaces the spare pool is holding — cut, based, and not yet anybody's.
 *
 * Here so the pool can be *seen*. A spare is deliberately an ordinary
 * workspace, which makes it indistinguishable on the board from one nobody
 * has opened; without this, the only way to tell whether a create was handed
 * a pre-cut tree would be to time it, which is the assertion
 * `docs/traps/e2e.md` warns against. The e2e flow reads this, and so can a
 * person wondering why the pool is empty.
 */
spare: Array<string>, workspaces: Array<WorkspaceView>, sessions: Array<SessionView>, 
/**
 * Past conversations in this checkout that orchd never started, newest first.
 * The rail lists them under the same fold as its own archive.
 */
external: Array<ExternalView>, prs: Array<PrView>, 
/**
 * Set when the last poll failed; the pane says so rather than showing an
 * empty list.
 */
pr_error: string | null, 
/**
 * The agent exited before its first turn and we did not stop it; see
 * `Inner::agent_error`. The board shows it in a bar, since the session it
 * happened to no longer exists.
 */
agent_error: string | null, 
/**
 * What the boot preflight found; see `Inner::machine`. The board shows it in
 * a bar, because these are the causes behind panes that read `unavailable`
 * and `off` and there is nowhere else in the window they appear.
 */
machine: Array<Warning>, pr_age_ms: number, 
/**
 * Monotonic counter of completed PR polls; see `Inner::pr_poll`.
 */
pr_poll: number, 
/**
 * A PR fetch is running. The pane spins its refresh icon while it is,
 * however the fetch was started.
 */
pr_polling: boolean, token_source: TokenSource | null, reviews: ReviewState, 
/**
 * Age of the last completed review poll, in ms. `None` before the first.
 * Mirrors `pr_age_ms`.
 */
reviews_age_ms: number, 
/**
 * Monotonic counter of completed review polls; see `Inner::reviews_poll`.
 */
reviews_poll: number, reviews_polling: boolean, 
/**
 * Ordered, for the same reason `WorkspaceView::branches` is sorted: the page
 * decides whether to repaint by comparing snapshot text, and a `HashMap`
 * rehash reorders these keys without changing a word of what they say.
 */
automation: { [key in string]: PrAutomation }, repos: Repos, 
/**
 * Main may hold more than one live session (`allow_several_in_main`).
 *
 * Sent because the rail decides whether to offer `+` on main, and the reason
 * it may is a setting the SPA cannot see any other way.
 */
several_in_main: boolean, 
/**
 * The base `behind`/`ahead` are measured against, e.g. `upstream/develop`.
 *
 * Sent because it is a setting: the divergence strip used to print the
 * default as a literal, so on any repo that had edited it the UI named a ref
 * the numbers did not come from.
 */
upstream_ref: string, 
/**
 * `docker compose` stack has running containers; `None` when this checkout
 * has no stack at all, which includes before the first probe. See
 * `Inner::stack_up` for why those are one answer.
 */
stack_up: boolean | null, 
/**
 * The worktree cut in flight: which step, and what it has printed. See
 * [`crate::model::CreateRun`].
 */
create_run: CreateRun | null, 
/**
 * A newer release than the running build, or `None`.
 */
update: UpdateInfo | null, 
/**
 * The app's own upgrade run: `running` while `mise upgrade` goes, then a tail
 * that is empty on success. Success means *installed*, not applied — this
 * process is still the old build, so the bar then asks for a restart.
 */
self_upgrade_run: UpgradeRun | null, 
/**
 * A newer Claude Code than the installed one, or `None`. Actionable in the
 * UI: the upgrade cannot disturb a session already running.
 */
agent_update: AgentUpdate | null, 
/**
 * The upgrade the update bar reports on, while it runs and after it fails.
 */
upgrade_run: UpgradeRun | null, 
/**
 * The running build's own version, for the settings panel. Always here,
 * unlike `update`, which only appears when there is something newer: "which
 * build am I on" is a question worth answering when the answer is "the
 * latest one".
 */
version: string, };

export type State = { "state": "starting" } | { "state": "working" } | { "state": "your_turn", since: { secs_since_epoch: number, nanos_since_epoch: number }, reason: TurnReason, } | { "state": "build_failing", summary: string, } | { "state": "error", message: string, } | { "state": "exited" } | { "state": "archived", resumable: boolean, };

/**
 * A story that exists in the tracker.
 *
 * Both halves come from the tool response and neither is ever constructed by
 * `format!`: the org slug in the URL belongs to your tracker workspace and the daemon has no
 * business knowing it.
 */
export type StoryRef = { 
/**
 * Short form, `sc-12345`. What the report shows.
 *
 * Private, with [`StoryRef::new`] the only way in, because the pair is agent
 * text that ends up as a link in a public comment: a value that has not been
 * through [`StoryRef::consistent`] must not be constructible outside this
 * module — `model` now, with `story` one of its callers. Serde is the
 * exception it cannot police — a `stories.json` written before the id was
 * checked deserializes straight past the constructor, which is why
 * [`Cache::get`] re-checks on the way out.
 */
id: string, 
/**
 * The clickable one, `https://app.shortcut.com/<org>/story/12345`.
 */
url: string, };

/**
 * Why a session is waiting on you.
 *
 * Running in auto-accept mode, permission prompts almost never fire; what
 * actually gates progress is Claude finishing a turn (§2). A completed turn is
 * not a quiet success, it is an idle agent.
 */
export type TurnReason = "turn_complete" | "asked_a_question" | "needs_permission" | "ready" | "interrupted";

/**
 * A release newer than what is running.
 */
export type UpdateInfo = { current: string, latest: string, url: string, 
/**
 * The mise tool that installed this binary, when one did.
 *
 * Still here because it is what `mise upgrade` is given, and because it is the
 * one install kind that cannot be read off a path — `update::app_providing_tool`
 * asks mise itself. What the *bar* branches on is [`Offer`], which this is only
 * one input to.
 */
tool: string | null, 
/**
 * What the bar may offer, and it is the whole of what the page decides from.
 *
 * The page used to derive this from `tool` being `None`, and got it wrong for
 * everything that is not mise: it told a `.deb`, a cask, an AppImage and a
 * checkout alike to "Run mise up". The daemon knows which install it is, so
 * the daemon says what can be done about it.
 */
offer: Offer, };

/**
 * An upgrade the daemon is running, or the failure it left behind.
 *
 * The run used to be a process in main's drawer, which was the wrong home twice:
 * the drawer is *this workspace's* processes, and upgrading the agent belongs to
 * no workspace — so from any worktree the run was invisible, and main's drawer
 * grew a tab that was not a process of main's at all. It reports through the same
 * bar that offered the button instead.
 */
export type UpgradeRun = { 
/**
 * The version being installed. Carried so the bar can say it even after the
 * check that found it has been refreshed away.
 */
to: string, running: boolean, 
/**
 * The tail of the output, for a run that failed. Empty while it runs, and
 * empty on success — which, with `running` false, is how the bar tells the two
 * finished states apart.
 *
 * Success used to clear the run outright, on the reasoning that the nudge
 * going away *is* the report. It is not: the sessions you have open go on
 * printing Claude Code's own upgrade notice, because they really are still the
 * old build, so a bar that vanishes silently against a terminal that still
 * says "update available" reads as a button that did nothing. It is reported,
 * and dismissed like any other.
 */
tail: string, };

export type WorkspaceKind = { "kind": "main" } | { "kind": "worktree", name: string, };

export type WorkspaceView = { id: string, path: string, kind: WorkspaceKind, is_main: boolean, occupant: string | null, 
/**
 * Every branch this workspace has ever held, never pruned (§2).
 *
 * Not "what is checked out" — see `branch` for that. The two were conflated
 * once, and the rail offered to swap with a main that was sitting on its base.
 */
branches: Array<string>, 
/**
 * What it has checked out now, or `None` before the first reconcile.
 */
branch: string | null, processes: Array<ProcessView>, 
/**
 * Managed processes this workspace declares that are not running — config
 * order, names only.
 *
 * The drawer built its tabs from `processes` alone, so anything with
 * `autostart: false` had no way into the app at all: the restart button the
 * config comment points at is drawn *on a tab*, and there was no tab. A
 * `docker compose up` you deliberately do not autostart still has to be
 * startable.
 */
stopped_processes: Array<string>, 
/**
 * Uncommitted work the rebase button parked, if any is parked.
 */
banked: BankedView | null, 
/**
 * Every file this workspace changed since it branched, committed work
 * included, plus anything untracked. What the changed-files pane lists.
 *
 * **Capped at [`CHANGED_CAP`]**, with the real number in `changed_total`.
 * That constant carries the measurement and the incident behind it.
 */
changed: Array<DiffFile>, 
/**
 * How many there really are, when `changed` is a prefix of them.
 *
 * Sent rather than inferred from the length, so the pane can say "500 of
 * 5,214" instead of quietly presenting a truncation as the whole answer —
 * the same honesty `unresolved_capped` buys the PR pane (§6).
 */
changed_total: number, 
/**
 * The commit the above is measured from: `merge-base(upstream, HEAD)`.
 */
changed_since: string | null, 
/**
 * Commits on `upstream/develop` this branch does not have. Drives the
 * rebase affordance.
 */
behind: number, ahead: number, rebasing: boolean, 
/**
 * Whether the four fields above have ever been measured for this workspace
 * — see [`crate::model::Tree::measured`].
 *
 * The pane needs it because the first sweep no longer finishes before the
 * window opens: without it an unmeasured worktree renders as "nothing
 * changed", which is the one thing a changed-files pane must not say when it
 * does not know.
 */
measured: boolean, };
