// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A newer agent build than the one installed.
 */
export type AgentUpdate = { 
/**
 * The mise tool name to upgrade — `claude-code` or `claude`, whichever this
 * checkout pins. Carried rather than assumed so the button upgrades the tool
 * that actually provides the binary.
 */
tool: string, current: string, latest: string, };

/**
 * How to rebuild a torn-down worktree so an archived session can be resumed (§2).
 */
export type ArchiveState = { "recovery": "recoverable", name: string, branch: string, head_sha: string, } | { "recovery": "transcript_only" };

/**
 * Work banked out of a rebase's way, as the pane needs it.
 *
 * The ref is sent rather than derived in the SPA, because it is the recovery a
 * person runs by hand (`git stash apply <at>`) and a second spelling of the name
 * is a second thing to keep in step.
 */
export type BankedView = { files: number, at: string, };

/**
 * One open checkout, as the page needs to see it.
 *
 * `token` is in here because the page holds one per checkout: every call names
 * the daemon it is for, and each daemon compares the token against its own. It is
 * the same value as the host's while one process serves both.
 */
export type Checkout = { 
/**
 * Canonical path, which is also the identity: `main_checkout` is resolved in
 * [`crate::config::Config::parse`], and comparing an unresolved path against
 * a resolved one silently matches nothing.
 */
path: string, 
/**
 * What to call this checkout on screen. Not a key — see [`Checkout::path`].
 *
 * Usually the last path component. **The parent segment is prefixed when two
 * open checkouts share a leaf** (`work/app` beside `play/app`), because the
 * leaf alone is the name in the rail header, the identity chip and every
 * message that says which checkout an action lands in — and two rows reading
 * `app` make all three useless. Only on a collision: a longer name in a 290px
 * rail is a cost most installs should not pay.
 *
 * Computed over the whole set by [`name_the_set`], so it changes when the set
 * does: closing the checkout that collided gives the other its short name
 * back.
 */
name: string, 
/**
 * Where its daemon answers.
 */
port: number, 
/**
 * What that daemon wants in `x-orch-token`.
 */
token: string, 
/**
 * False for a checkout whose daemon is down. Always true while the only
 * daemon is the process serving this page: a host cannot outlive itself.
 */
live: boolean, 
/**
 * The repository this checkout's daemon polls, `owner/name`, when it has one.
 *
 * The key [`Host::add_checkout`] refuses a second checkout on — see
 * [`polled_repo`] for why it is this value and not the `Repos` pair. `None`
 * for a checkout with no matching remote, and two of those are allowed:
 * refusing them would refuse every local-only checkout after the first.
 */
repo: string | null, 
/**
 * The other open checkout polling the same repository, when there is one.
 *
 * **A clash `add` could not see.** `add` derives the identity from whatever
 * config exists; the daemon derives it from the real `upstream_remote` and
 * reports it, which is the only authoritative answer. A disagreement between
 * the two is named here rather than tolerated in silence — the two daemons
 * cannot see each other's fix runs, and nothing else would ever say so.
 */
clash: string | null, };

export type Checks = "passing" | "failing" | "pending" | "unknown";

/**
 * One comment in a review thread.
 */
export type Comment = { 
/**
 * REST id. The reply endpoint is keyed on this, not on the GraphQL node id.
 */
database_id: bigint, author: string, body: string, created_at: string, url: string, 
/**
 * The anchored patch text. GitHub hangs it off every comment; only the
 * first one's is worth rendering, so `Thread::diff_hunk` reads that.
 */
diff_hunk: string | null, 
/**
 * You have 👍'd this comment.
 *
 * Fetched because the poll and the resolve flow have to agree on what a
 * thumbs-up means, and only the poll could see one: the detailed thread query
 * did not ask for reactions, so `is_answerable` re-offered every thread the
 * flow had already answered with a 👍 — the review's §3 finding.
 */
viewer_thumbed: boolean, };

export type DiffFile = { path: string, 
/**
 * Verbatim from `--name-status`: M, A, D, R…, C…
 */
status: string, added: number, deleted: number, binary: boolean, 
/**
 * Whether the client should fetch hunks without being asked.
 */
eager: boolean, 
/**
 * Present for renames.
 */
old_path: string | null, 
/**
 * Whether this file has changes in the **index**, and whether it has changes
 * in the **working tree** — `git status`'s two answers, joined on by path.
 *
 * **Not derivable from `status` above, and that is the point.** This list is
 * `git diff <merge-base>`, so most rows on a PR branch differ from the base
 * because of a *commit* and are otherwise clean. Offering "discard changes"
 * against that list would be offering to throw away nothing on some rows and
 * a commit's content on others, from a menu that cannot tell them apart. The
 * pane's git verbs are drawn from these two instead, so what is offered is
 * exactly what exists: staged → unstage, working-tree → stage, discard.
 *
 * Both `false` is the ordinary case (changed in a commit, clean on disk) and
 * gets no verbs at all.
 */
staged: boolean, unstaged: boolean, };

export type DiffSummary = { base: string, files: Array<DiffFile>, added: number, deleted: number, };

/**
 * A write that was attempted and refused. `error` is `gh`'s own words.
 */
export type Failed = { thread_id: string, label: string, what: What, error: string, };

export type FileDiff = { path: string, hunks: Array<Hunk>, binary: boolean, truncated: boolean, };

/**
 * A path the batch will touch, with its line counts — the data behind the
 * card's `will write renovate.json5 +2 −1` label.
 */
export type FileStat = { path: string, added: number, deleted: number, };

/**
 * Why a triage run cannot start.
 *
 * These are the worktree-readiness gates: the review flow writes into this
 * worktree, and every guarantee downstream — the check ladder, the complete file
 * list, "only what you approved" — assumes the tree starts clean. CI colour and
 * a merge conflict deliberately do **not** appear here; they are signals about a
 * future merge and never touch the branch-local machinery.
 */
export type Gate = { "gate": "dirty", files: Array<string>, } | { "gate": "rebasing" } | { "gate": "fix_pr_running" };

export type Health = { "health": "starting" } | { "health": "ok" } | { "health": "failing", summary: string, } | { "health": "dead" };

export type Hunk = { old_start: number, new_start: number, header: string, 
/**
 * Unchanged lines skipped before this hunk, so the client can render a
 * fold bar and expand on click.
 */
gap_before: number, rows: Array<Row>, };

/**
 * A question a running session is blocked on.
 *
 * Hooks are one-way and the only daemon-to-agent path is a pty write, so this
 * is the first thing that travels *back*: the agent posts a question, blocks on
 * a long poll, and the answer you give in the overlay is what its tool call
 * returns. Deliberately structured rather than free text, so the overlay renders
 * buttons instead of asking you to type into a terminal you cannot see.
 */
export type Interaction = { id: string, 
/**
 * What the agent is working on, so the card can say which thread this is
 * about without the agent having to repeat it in the question.
 */
thread_id: string | null, question: string, 
/**
 * Optional context: a diff, a file, the reviewer's words. Rendered as-is.
 */
detail: string | null, 
/**
 * What you may answer. Never empty: an open question with no options is a
 * prompt for prose the overlay has no box for.
 */
options: Array<InteractionOption>, asked_at: { secs_since_epoch: number, nanos_since_epoch: number }, 
/**
 * Set when you answer, which is what releases the agent's poll.
 */
answer: string | null, 
/**
 * The words you typed, when the option you picked asked for some.
 */
answer_text: string | null, };

export type InteractionOption = { 
/**
 * What comes back to the agent. Its own vocabulary, not the label, so the
 * prompt can branch on a stable word while the card stays readable.
 */
value: string, label: string, sub: string, 
/**
 * This option wants words with it: the escape hatch, for when none of the
 * others fit. The *value* still comes from the agent's own vocabulary, so it
 * branches on a word it wrote; your text rides along as the reason.
 */
free: boolean, };

/**
 * Something that is now true on GitHub.
 */
export type Landed = { thread_id: string, 
/**
 * `renovate.json5:161 · bob`, for the report's left column.
 */
label: string, what: What, 
/**
 * It was already there, so nothing was sent. The distinction matters on a
 * retry: "posted" and "already posted" read the same to a reviewer but not
 * to someone deciding whether the retry worked.
 */
already: boolean, 
/**
 * Set on a `Story` row. Not a bare id on the struct, which would be
 * meaningless next to a reply or a reaction — and the report needs the URL
 * too, to show what the reply will actually link to.
 */
story: StoryRef | null, };

/**
 * The batch stopped to wait for you.
 *
 * Reached only when a decision chose `Manual`. The accepted patches are written
 * and committed by then, so you edit a tree that already reflects every other
 * decision — often *why* this thread needed hands. **Nothing has been pushed and
 * nothing posted**, so backing out costs only the local commit.
 */
export type ManualPhase = { 
/**
 * The commit the accepted patches landed in. `/manual/done` checks `HEAD`
 * against it, which is what keeps the phase from resuming onto a branch that
 * moved underneath it.
 *
 * Kept in step with the worktree by `update_phase_head` and written to disk with
 * the rest of the phase, because `fold_in` rewrites shas in both its arms — after
 * a fold the old sha is not even an ancestor of `HEAD`, so nothing can re-derive
 * which commit was ours.
 */
committed: string, 
/**
 * What was already written, for the phase screen's first line.
 */
files: Array<FileStat>, amend: string | null, threads: Array<ManualThread>, 
/**
 * A digest of the decisions half one resolved.
 *
 * The resume re-supplies the whole batch and the daemon re-resolves it from
 * scratch, with only `committed == HEAD` checked — and that says nothing about
 * *which* decisions produced that commit. A decision half one never saw would
 * otherwise post a reply describing code that was never applied.
 */
decisions: string, 
/**
 * Is there a phase here to finish, or only a push to remember?
 *
 * [`remember_push`] needs somewhere durable to say "the daemon pushed this,
 * for these decisions", so a retry after a failed reply is not refused as
 * "the branch moved since triage"; the phase store is the one per-PR record a
 * batch has. But a batch that never stopped for the manual phase has no phase,
 * so that record went in as an entry with empty `threads` — and emptiness was
 * the only thing telling the two apart.
 *
 * Nothing read it that way. The boot log announced "manual phase still open",
 * the review payload served it, and the SPA adopted it: it dropped you on a
 * manual screen with no rows, where `threads.every(…)` is vacuously true and
 * `continue · push and post` was therefore enabled. Worse, the record is
 * cleared only when nothing failed, so it survived exactly when it was wrong.
 * Hence a field rather than a shape a reader has to infer.
 */
open: boolean, };

/**
 * A thread the human said they would handle themselves.
 */
export type ManualThread = { thread_id: string, label: string, 
/**
 * The reviewer's own words, so the phase screen needs no second fetch.
 */
comment: string, 
/**
 * What the card's box held. A starting point, not the comment — you cannot
 * describe work you have not done yet, which is why the real one is written
 * in the phase.
 */
draft: string, };

/**
 * The PR pass a session was started to run, when it was started as one.
 *
 * **One field rather than two.** `pr` and `command` are inseparable — a pass with
 * no PR means nothing, and a PR with no pass is just a session that happens to be
 * on a branch — so they live in one `Option` and the impossible pair cannot be
 * written down.
 *
 * **What reads `command`, and why a skill cannot answer it.** The instructions
 * live in `skills/` now, so this is no longer "which prompt did the daemon type".
 * It is the five things the daemon has to know *around* the agent rather than
 * inside it: which settle path an exit dispatches to (`spawn::watch_session_exit`),
 * which spawn is handed `ORCH_POST_TOKEN` (`triage::posts_proposals`), that a
 * resolve run may not ask questions (`api::ask`), that one triage pass per PR is
 * enough (`triage::is_triage_of`), and which PR the review bar is reporting on.
 * Every one of those happens before the first turn or after the last.
 *
 * It carries **no opinion about attention.** `Kind::Automation` used to, and the
 * rail demoted a running pass and painted it teal on the strength of it — which
 * went wrong the moment a pass meant "a pane you are watching" as well as "a run
 * nobody is". A session is a session; its state says whether it wants you.
 */
export type Pass = { pr: number, command: string, };

/**
 * One complete way of answering a thread.
 */
export type Position = { label: string, 
/**
 * The line under the label — why you would pick this one.
 */
sub: string, stance: Stance, 
/**
 * A unified diff, exactly as `git diff` printed it in the agent's scratch
 * worktree. Its presence is what "this position changes code" means; there
 * is no second field that could disagree with it.
 */
patch: string | null, 
/**
 * Present iff `stance.writes_reply()`. For a story position it must contain
 * `{story}`, substituted once the story exists.
 */
reply: string | null, story: StoryDraft | null, };

/**
 * What the failure panel renders.
 *
 * `refused` is the local half saying no — the ladder found a stale patch, the
 * hooks rewrote a file, pre-commit failed. Nothing was committed and nothing was
 * pushed, so every other field is empty and the screen is panel 7 rather than
 * panel 8.
 */
export type PostReport = { refused: string | null, 
/**
 * Whether pressing the same button again could succeed once you have acted on
 * `refused`.
 *
 * A stray file or a failing hook is something you fix and retry; the branch
 * having moved under an open phase is not — that sha will never match again, so
 * restoring the phase for it pins you to a screen whose only button is
 * guaranteed to fail. The SPA needs to tell those apart and the message alone
 * cannot.
 */
retryable: boolean, 
/**
 * Set when the batch is waiting on you. Everything else is empty: the outward
 * half has not run.
 */
manual: ManualPhase | null, 
/**
 * The complete file list the batch wrote, from `git apply --numstat`.
 */
files: Array<FileStat>, 
/**
 * How the fold resolved, including when it fell back to a HEAD amend.
 */
amend: string | null, 
/**
 * The sha now on origin. `Some` means the code cannot be taken back.
 */
pushed: string | null, landed: Array<Landed>, failed: Array<Failed>, skipped: Array<Skipped>, rerequested: Array<string>, held_back: Array<Skipped>, };

export type Pr = { number: number, title: string, url: string, head_ref: string, 
/**
 * The head branch's repo, `owner/name`, for naming it in a refusal.
 */
head_repo: string | null, 
/**
 * May you push to that repo?
 *
 * This is what the `fix-pr` authorship guard asks, and it replaced "is the
 * head repo's owner your login". That test was wrong in both directions: on
 * an org PR the owner is the org, so it refused every PR and made `fix-pr`
 * unusable outside a fork layout — while a same-repo PR passed it only
 * because you happened to own the repo, not because it had established
 * anything about a force-push.
 *
 * Repo-level, so it does not promise a given *branch* is force-pushable;
 * `src/guard.rs` is the other half of that pair (`--force-with-lease` only,
 * never the base branch). `None` means GitHub did not say, and the guard fails
 * closed on it.
 */
head_pushable: boolean | null, base_ref: string, is_draft: boolean, 
/**
 * `MERGEABLE` / `CONFLICTING` / `UNKNOWN`.
 */
mergeable: string, merge_state: string, checks: Checks, 
/**
 * Head commit. `fix-pr` amends and rebases, so this moves on every
 * internal attempt — it is an identity for "has the branch changed since
 * the run gave up", not a provenance record (§8).
 */
head_sha: string | null, 
/**
 * GitHub's sense of resolved — a conversation the comment author closed.
 * Not to be confused with `/api/pr/:number/resolve-run`, which is *our* flow for
 * answering threads and deliberately never closes one.
 */
unresolved: number, 
/**
 * True when `reviewThreads` had another page, so `unresolved` is a floor.
 * Rendered as `50+` rather than `50`, so an under-count cannot silently
 * hide work (§6).
 */
unresolved_capped: boolean, 
/**
 * Of those, the ones whose last word is not yours and which you have not
 * 👍'd. This is the number the rail acts on; `unresolved` is GitHub's.
 */
awaiting_you: number, changes_requested: boolean, 
/**
 * Whether this PR is waiting on you, decided here rather than in four
 * places that each got it slightly differently.
 *
 * A thread you have answered is not your turn even though GitHub still
 * calls it unresolved — closing it is the reviewer's button. A
 * changes-requested review counts only when there are no threads to answer,
 * which is the shape of an objection written in the review body: with
 * threads present it stays set until the reviewer looks again, and treating
 * that as your turn is what made an answered PR sit there amber.
 */
needs_you: boolean, 
/**
 * PRs stacked directly on this one.
 */
children: Array<number>, };

/**
 * Per-PR automation state (§8).
 *
 * Retry lives in the prompt, not here: `fix-pr` amends and rebases, so the head
 * SHA changes on every internal attempt and SHA-based provenance is impossible
 * *and* unnecessary. The daemon's job is only to avoid starting a second run
 * and to be honest about a run that gave up.
 */
export type PrAutomation = { "state": "running", session: string, started: { secs_since_epoch: number, nanos_since_epoch: number }, } | { "state": "exhausted", 
/**
 * The head this exhaustion is measured against, once anything knows it.
 *
 * `None` means "not established yet", and the next poll adopts whatever
 * it finds. Two things wrote a wrong answer here before, and both
 * cleared the record on the very next poll — erasing the "gave up, wants
 * you" signal the run had just set. `settle` copied the head from the
 * *previous* poll, which the run's own force-push had already moved past;
 * and a crashed run was demoted with `""`, which can never equal a real
 * sha. Neither could be told apart from you moving the branch.
 */
at_head: string | null, at: { secs_since_epoch: number, nanos_since_epoch: number }, };

export type PrView = { rank: number, 
/**
 * The workspace whose branch set contains this PR's head ref.
 */
workspace: string | null, 
/**
 * A live session in that workspace, so the row can act as a jump link.
 */
session: string | null, number: number, title: string, url: string, head_ref: string, 
/**
 * The head branch's repo, `owner/name`, for naming it in a refusal.
 */
head_repo: string | null, 
/**
 * May you push to that repo?
 *
 * This is what the `fix-pr` authorship guard asks, and it replaced "is the
 * head repo's owner your login". That test was wrong in both directions: on
 * an org PR the owner is the org, so it refused every PR and made `fix-pr`
 * unusable outside a fork layout — while a same-repo PR passed it only
 * because you happened to own the repo, not because it had established
 * anything about a force-push.
 *
 * Repo-level, so it does not promise a given *branch* is force-pushable;
 * `src/guard.rs` is the other half of that pair (`--force-with-lease` only,
 * never the base branch). `None` means GitHub did not say, and the guard fails
 * closed on it.
 */
head_pushable: boolean | null, base_ref: string, is_draft: boolean, 
/**
 * `MERGEABLE` / `CONFLICTING` / `UNKNOWN`.
 */
mergeable: string, merge_state: string, checks: Checks, 
/**
 * Head commit. `fix-pr` amends and rebases, so this moves on every
 * internal attempt — it is an identity for "has the branch changed since
 * the run gave up", not a provenance record (§8).
 */
head_sha: string | null, 
/**
 * GitHub's sense of resolved — a conversation the comment author closed.
 * Not to be confused with `/api/pr/:number/resolve-run`, which is *our* flow for
 * answering threads and deliberately never closes one.
 */
unresolved: number, 
/**
 * True when `reviewThreads` had another page, so `unresolved` is a floor.
 * Rendered as `50+` rather than `50`, so an under-count cannot silently
 * hide work (§6).
 */
unresolved_capped: boolean, 
/**
 * Of those, the ones whose last word is not yours and which you have not
 * 👍'd. This is the number the rail acts on; `unresolved` is GitHub's.
 */
awaiting_you: number, changes_requested: boolean, 
/**
 * Whether this PR is waiting on you, decided here rather than in four
 * places that each got it slightly differently.
 *
 * A thread you have answered is not your turn even though GitHub still
 * calls it unresolved — closing it is the reviewer's button. A
 * changes-requested review counts only when there are no threads to answer,
 * which is the shape of an objection written in the review body: with
 * threads present it stays set until the reviewer looks again, and treating
 * that as your turn is what made an answered PR sit there amber.
 */
needs_you: boolean, 
/**
 * PRs stacked directly on this one.
 */
children: Array<number>, };

export type ProcKind = { "kind": "managed", command: Array<string>, } | { "kind": "shell", exit_code: number | null, };

export type ProcessView = { id: string, name: string, kind: ProcKind, health: Health, cwd: string, alive: boolean, exit_code: number | null, };

/**
 * One thread's triage: what the agent made of it, and the ways out.
 */
export type Proposal = { thread_id: string, 
/**
 * You already replied here and the reviewer came back. The card flags it,
 * because a new reply has to stay consistent with what you said before.
 */
continued: boolean, 
/**
 * The agent's assessment: is the reviewer right, what breaks either way.
 */
read: string, 
/**
 * The command it ran in its scratch worktree and what that showed. Absent
 * only when no position changes code — there is nothing to re-prove.
 */
verified: string | null, 
/**
 * Index into `positions` of the one to pre-select.
 */
recommend: number, 
/**
 * Named `positions` on the wire too; the agent's schema calls them options,
 * which collides with `Option`.
 */
positions: Array<Position>, };

/**
 * A whole triage run's output.
 */
export type ProposalSet = { 
/**
 * The PR head the patches were generated against. Re-checked before
 * writing: a force-push in between invalidates every diff.
 */
base_sha: string, proposals: Array<Proposal>, };

export type Repos = { 
/**
 * Where PRs are opened, e.g. `acme/monorepo`.
 */
upstream: string | null, 
/**
 * Where branches are pushed, e.g. `you/monorepo` (§6's fork flow).
 */
fork: string | null, };

/**
 * PRs where your review is requested — other people's work (§6b).
 *
 * The shape came from an existing `mise run reviews --json` task, which applies
 * a richer ranking than §6b describes: prio labels, personal versus team
 * request, re-review detection, reviewer-count tiebreak. The daemon consumes
 * that shape rather than imposing the one §6b invented.
 */
export type Review = { number: number, title: string, url: string, author: string, 
/**
 * Age in hours, however the source expressed it.
 */
age_hours: number, 
/**
 * Source rank: 0 stopper, 1 prio, 2 requested of you, 3 of your team,
 * 4 re-review, 5 other, 6 sidequest.
 */
prio: number, needs_re_review: boolean, is_draft: boolean, 
/**
 * `conflicts`, `failing checks`, … — non-empty means it is waiting on
 * someone else and sinks to the bottom.
 */
blockers: Array<string>, reviewers: number, 
/**
 * Review cost. Absent until the source grows `changedFiles`; the column is
 * omitted rather than faked (see docs/reviews-json.md).
 */
changed_files: number | null, checks: string | null, };

export type ReviewQueue = { login: string, actionable: Array<Review>, blocked: Array<Review>, total: number, skipped: number, };

/**
 * A pane that cannot be trusted must say so.
 *
 * Silently showing zero reviews when the command is broken is the one failure
 * that would actually cost a colleague a day (§6b), so a non-zero exit,
 * unparseable output or an unknown `version` all land here instead.
 */
export type ReviewState = { "state": "ok" } & ReviewQueue | { "state": "degraded", reason: string, } | { "state": "pending" } | { "state": "off" };

export type Row = { kind: RowKind, old: number | null, new: number | null, text: string, 
/**
 * Byte ranges within `text` that actually differ, for word-level
 * highlighting. Computed here so the browser's main thread never pays for
 * it (§5). Non-overlapping and in ascending order.
 */
words: [number, number][] | undefined, };

export type RowKind = "context" | "del" | "add";

export type RunThreadView = { thread_id: string, location: string, status: ThreadStatus, commit: string | null, note: string | null, };

/**
 * What the overview shows about a run: one row per thread, in plan order.
 */
export type RunView = { session: string, threads: Array<RunThreadView>, 
/**
 * Why the run is over, when it is. `null` means the session is still on it.
 */
ended: string | null, 
/**
 * Commits on the run's branch that its remote does not have.
 *
 * The one thing the overview could not say before: a run finishes with the
 * reviewers answered and the work sitting on nobody's branch but yours, and
 * the only mention of it was whatever prose the agent chose to write in the
 * pane. Measured at the last reconcile of the run's own worktree, so it
 * counts a push made anywhere — not a flag the push button sets.
 */
unpushed: number, };

export type SessionView = { id: string, workspace: string, state: State, pass: Pass | null, 
/**
 * What to call this session — the name you gave it, else Claude Code's own
 * ai-title (`Session::label`). The panes read this and stay out of the
 * precedence.
 */
title: string | null, 
/**
 * Only the name you typed, so the rename prompt can offer it back and an
 * empty answer can mean "go back to the ai-title" rather than "freeze it".
 */
name: string | null, cwd: string, 
/**
 * The branch this conversation is about ([`Session::branch`]), not the tree it
 * sits in. Sent so `orch ls` can answer the question its columns could not:
 * whether two sessions can safely work in parallel. A shared `cwd` means one
 * git index, and two rows on one branch means one branch — and neither was
 * visible from id, workspace and state.
 */
branch: string | null, rank: number, 
/**
 * Whether this is idle time worth counting. A session you just opened is
 * idle but not waiting on you in the sense the rail exists to surface.
 */
wants_attention: boolean, 
/**
 * How long this session has been waiting on you. With 4-6 sessions the
 * cost of the whole tool is measured in agent-minutes spent idle (§2).
 */
waiting_ms: number, created_ms: number, alive: boolean, dirty_count: number, boundary_violations: Array<string>, resumable: boolean, 
/**
 * Whether a turn ever happened here — the SPA gates Fork and the nudge on it,
 * and lists an archived row only when it is true. Named for the file it used to
 * stat; it is now the `had_a_turn` bit, which answers the same question the
 * callers actually meant without a per-snapshot read.
 */
has_transcript: boolean, 
/**
 * What this session is blocked on, waiting for you. The overlay renders it;
 * everything else ignores it.
 */
interaction: Interaction | null, 
/**
 * The conversation this one was cut from. A fork inherits its parent's
 * title, so without this two rows read the same and neither says why.
 */
forked_from: string | null, 
/**
 * Whether this session still owes you the rest of a turn. The nudge is only
 * true of these; every other resumed session is sitting at its prompt done.
 */
interrupted: boolean, 
/**
 * A review that ended by handing its PR's checks to a `fix-pr` run.
 *
 * Here rather than left for the overlay to infer, because the two facts it
 * would have to infer it from arrive apart: the session is marked `Exited`
 * straight away and the run's record only exists once `ensure_pr_worktree` and
 * a spawn have finished. In that gap the overlay would put its finished-review
 * report up and then take it away again a second later, which is a worse thing
 * to show than either state.
 */
handed_off: boolean, };

/**
 * A write that was never tried, and what it is waiting on.
 */
export type Skipped = { label: string, what: What, waiting_on: string, };

/**
 * What the SPA receives on every tick.
 *
 * `TS` is derived under `cfg(test)` only, so `ts-rs` is a dev-dependency and
 * nothing about it reaches the shipped binary. `cargo test` writes
 * `web/snapshot.d.ts` from these definitions, and `web/app.js` type-checks
 * against it — which is what stops a field being renamed here and read by the
 * old name there, the way `pr_age_ms` sat unread and the divergence strip named
 * a ref it had not measured.
 */
export type Snapshot = { 
/**
 * The configured tracker's MCP server name, or `None` for no tracker.
 *
 * Here rather than on `/api/config` because it is read-only to the SPA: a
 * tracker is three fields (`config::Tracker`), one of them a per-site host, so
 * the settings pane shows it and does not offer it — and `Settings` leaves it
 * out so a write of the whole struct cannot replace a hand-edited one.
 */
tracker_server: string | null, workspaces: Array<WorkspaceView>, sessions: Array<SessionView>, prs: Array<PrView>, 
/**
 * Set when the last poll failed; the pane says so rather than showing an
 * empty list.
 */
pr_error: string | null, pr_age_ms: number, 
/**
 * Monotonic counter of completed PR polls; see `Inner::pr_poll`.
 */
pr_poll: number, 
/**
 * A PR fetch is running. The pane spins its refresh icon while it is,
 * however the fetch was started.
 */
pr_polling: boolean, token_source: TokenSource | null, reviews: ReviewState, 
/**
 * Age of the last completed review poll, in ms. `None` before the first.
 * Mirrors `pr_age_ms`.
 */
reviews_age_ms: number, 
/**
 * Monotonic counter of completed review polls; see `Inner::reviews_poll`.
 */
reviews_poll: number, reviews_polling: boolean, automation: { [key in string]: PrAutomation }, repos: Repos, 
/**
 * Main may hold more than one live session (`allow_several_in_main`).
 *
 * Sent because the rail decides whether to offer `+` on main, and the reason
 * it may is a setting the SPA cannot see any other way.
 */
several_in_main: boolean, 
/**
 * The base `behind`/`ahead` are measured against, e.g. `upstream/develop`.
 *
 * Sent because it is a setting: the divergence strip used to print the
 * default as a literal, so on any repo that had edited it the UI named a ref
 * the numbers did not come from.
 */
upstream_ref: string, 
/**
 * `docker compose` stack has running containers; `None` before first probe.
 */
stack_up: boolean | null, 
/**
 * A newer release than the running build, or `None`.
 */
update: UpdateInfo | null, 
/**
 * The app's own upgrade run: `running` while `mise upgrade` goes, then a tail
 * that is empty on success. Success means *installed*, not applied — this
 * process is still the old build, so the bar then asks for a restart.
 */
self_upgrade_run: UpgradeRun | null, 
/**
 * A newer Claude Code than the installed one, or `None`. Actionable in the
 * UI: the upgrade cannot disturb a session already running.
 */
agent_update: AgentUpdate | null, 
/**
 * The upgrade the update bar reports on, while it runs and after it fails.
 */
upgrade_run: UpgradeRun | null, 
/**
 * Resolve runs in flight, by PR: what each thread's outcome was so far. The
 * overview reads this rather than the report of a batch that has finished,
 * because a run is watchable while it happens.
 */
resolve_runs: { [key in string]: RunView }, 
/**
 * How far each triage pass has read, by PR. The review bar counts with it.
 */
triage: { [key in string]: TriageProgress }, 
/**
 * The running build's own version, for the settings panel. Always here,
 * unlike `update`, which only appears when there is something newer: "which
 * build am I on" is a question worth answering when the answer is "the
 * latest one".
 */
version: string, };

/**
 * What you are saying back to the reviewer.
 *
 * One of the three things decided per thread, and deliberately only that. It
 * used to be `Does`, which bundled the stance together with whether code gets
 * written and who writes it — so "agree, and I will fix it by hand" had no
 * spelling. Code is now simply whether the position carries a patch, and who
 * writes it is [`Mode`], chosen by the human rather than proposed by the agent.
 */
export type Stance = "agree" | "reply" | "story";

export type State = { "state": "starting" } | { "state": "working" } | { "state": "your_turn", since: { secs_since_epoch: number, nanos_since_epoch: number }, reason: TurnReason, } | { "state": "build_failing", summary: string, } | { "state": "error", message: string, } | { "state": "exited" } | { "state": "archived", resumable: boolean, };

/**
 * A story to file, when a position defers the point rather than answering it.
 */
export type StoryDraft = { title: string, body: string, };

/**
 * A story that exists in the tracker.
 *
 * Both halves come from the tool response and neither is ever constructed by
 * `format!`: the org slug in the URL belongs to your tracker workspace and the daemon has no
 * business knowing it.
 */
export type StoryRef = { 
/**
 * Short form, `sc-12345`. What the report shows.
 *
 * Private, with [`StoryRef::new`] the only way in, because the pair is agent
 * text that ends up as a link in a public comment: a value that has not been
 * through [`StoryRef::consistent`] must not be constructible outside this
 * module. Serde is the exception it cannot police — a `stories.json` written
 * before the id was checked deserializes straight past the constructor, which
 * is why [`Cache::get`] re-checks on the way out.
 */
id: string, 
/**
 * The clickable one, `https://app.shortcut.com/<org>/story/12345`.
 */
url: string, };

/**
 * An unresolved conversation on a PR.
 */
export type Thread = { 
/**
 * `PRRT_…`. **Not** a resolve target — closing a thread is the comment
 * author's button, never ours — but the join key between a thread and the
 * finding the triage agent returns for it.
 */
id: string, path: string | null, 
/**
 * `null` on an outdated thread; the finding can still stand.
 */
line: number | null, start_line: number | null, original_line: number | null, is_resolved: boolean, is_outdated: boolean, comments: Array<Comment>, 
/**
 * [`Thread::is_answerable`] against the fetch's own viewer, resolved by
 * [`Threads::mark_answerable`] so the SPA does not have to reimplement the
 * rule. Always false straight out of parsing, which has no viewer to judge
 * by.
 */
answerable: boolean, };

/**
 * Where one thread of a run has got to.
 *
 * The states a thread can actually be in, rather than done/not-done: a run that
 * answered four threads, held one back and could not apply a sixth has five
 * different outcomes to account for, and an overview that says "5 of 6" about it
 * is hiding the only rows worth reading.
 */
export type ThreadStatus = "pending" | "committed" | "replied" | "held" | "manual" | "words_only" | "needs_you";

/**
 * Where the daemon's GitHub token came from.
 *
 * §6 wants a fine-grained PAT with **read scopes only** — `pull_requests`,
 * `checks`, `contents`, `metadata`. The daemon never pushes; `fix-pr` pushes
 * through the agent's own git credentials, so any write scope here is
 * unnecessary blast radius.
 */
export type TokenSource = "env" | "file" | "gh_cli";

/**
 * A resolve run: the session doing it, and the decisions it carries.
 *
 * How far a triage pass has read, and whether it has handed anything over.
 *
 * **The agent is the only thing that can count this.** The daemon knows how many
 * threads it handed over, but the read is a judgement per thread rather than a
 * loop the daemon drives, so the skill posts after each one and this is where it
 * lands. `total` is the agent's own count of what it means to read, which can be
 * fewer than the threads on the PR: an answered thread is skipped, and a bar
 * counting those would never reach its end.
 *
 * In memory only, and deliberately: it is a progress bar for a pass that ends
 * with its session. The proposals themselves are stored, so a restart loses the
 * caption and not the work.
 */
export type TriageProgress = { 
/**
 * Threads read so far.
 */
done: number, 
/**
 * Threads this pass means to read.
 */
total: number, 
/**
 * The proposals have landed, so the cards are there to go to.
 */
posted: boolean, 
/**
 * The session doing the reading, so the bar can refuse to caption another
 * session's pane.
 */
session: string, };

/**
 * Why a session is waiting on you.
 *
 * Running in auto-accept mode, permission prompts almost never fire; what
 * actually gates progress is Claude finishing a turn (§2). A completed turn is
 * not a quiet success, it is an idle agent.
 */
export type TurnReason = "turn_complete" | "asked_a_question" | "needs_permission" | "ready" | "interrupted";

/**
 * A release newer than what is running.
 */
export type UpdateInfo = { current: string, latest: string, url: string, 
/**
 * The mise tool that installed this binary, when one did.
 *
 * What decides whether the bar can offer a button at all: `Some` is an install
 * the app can upgrade itself (`mise upgrade <tool>`), `None` is a `.deb`, an
 * AppImage, a `.dmg` or a checkout, where the honest offer is the release link
 * it already had. Resolved by `update::app_providing_tool` at check time,
 * off-thread, because it shells mise.
 */
tool: string | null, };

/**
 * An upgrade the daemon is running, or the failure it left behind.
 *
 * The run used to be a process in main's drawer, which was the wrong home twice:
 * the drawer is *this workspace's* processes, and upgrading the agent belongs to
 * no workspace — so from any worktree the run was invisible, and main's drawer
 * grew a tab that was not a process of main's at all. It reports through the same
 * bar that offered the button instead.
 */
export type UpgradeRun = { 
/**
 * The version being installed. Carried so the bar can say it even after the
 * check that found it has been refreshed away.
 */
to: string, running: boolean, 
/**
 * The tail of the output, for a run that failed. Empty while it runs, and
 * empty on success — which, with `running` false, is how the bar tells the two
 * finished states apart.
 *
 * Success used to clear the run outright, on the reasoning that the nudge
 * going away *is* the report. It is not: the sessions you have open go on
 * printing Claude Code's own upgrade notice, because they really are still the
 * old build, so a bar that vanishes silently against a terminal that still
 * says "update available" reads as a button that did nothing. It is reported,
 * and dismissed like any other.
 */
tail: string, };

/**
 * A single outward write, named the way the report renders it.
 */
export type What = "story" | "reply" | "thumbs_up" | "rerequest";

export type WorkspaceKind = { "kind": "main" } | { "kind": "worktree", name: string, };

export type WorkspaceView = { id: string, path: string, kind: WorkspaceKind, is_main: boolean, occupant: string | null, 
/**
 * Every branch this workspace has ever held, never pruned (§2).
 *
 * Not "what is checked out" — see `branch` for that. The two were conflated
 * once, and the rail offered to swap with a main that was sitting on its base.
 */
branches: Array<string>, 
/**
 * What it has checked out now, or `None` before the first reconcile.
 */
branch: string | null, processes: Array<ProcessView>, 
/**
 * Managed processes this workspace declares that are not running — config
 * order, names only.
 *
 * The drawer built its tabs from `processes` alone, so anything with
 * `autostart: false` had no way into the app at all: the restart button the
 * config comment points at is drawn *on a tab*, and there was no tab. A
 * `docker compose up` you deliberately do not autostart still has to be
 * startable.
 */
stopped_processes: Array<string>, 
/**
 * Uncommitted work the rebase button parked, if any is parked.
 */
banked: BankedView | null, 
/**
 * Every file this workspace changed since it branched, committed work
 * included, plus anything untracked. What the changed-files pane lists.
 *
 * **Capped at [`CHANGED_CAP`]**, with the real number in `changed_total`.
 * That constant carries the measurement and the incident behind it.
 */
changed: Array<DiffFile>, 
/**
 * How many there really are, when `changed` is a prefix of them.
 *
 * Sent rather than inferred from the length, so the pane can say "500 of
 * 5,214" instead of quietly presenting a truncation as the whole answer —
 * the same honesty `unresolved_capped` buys the PR pane (§6).
 */
changed_total: number, 
/**
 * The commit the above is measured from: `merge-base(upstream, HEAD)`.
 */
changed_since: string | null, 
/**
 * Commits on `upstream/develop` this branch does not have. Drives the
 * rebase affordance.
 */
behind: number, ahead: number, rebasing: boolean, 
/**
 * Whether the four fields above have ever been measured for this workspace
 * — see [`crate::model::Tree::measured`].
 *
 * The pane needs it because the first sweep no longer finishes before the
 * window opens: without it an unmeasured worktree renders as "nothing
 * changed", which is the one thing a changed-files pane must not say when it
 * does not know.
 */
measured: boolean, };
